/*********************************************************************
*  
*   IAR PowerPac
*
*   (c) Copyright IAR Systems 2008.  All rights reserved.
*
**********************************************************************
----------------------------------------------------------------------
File    : FLASH.mac
Purpose : Setup file for LPC2xxx and IAR CSpy
          Feel free to modify this file acc. to your target system.
--------  END-OF-HEADER  ---------------------------------------------
*/

/*********************************************************************
*
*       Init()
*
* Function description
*   Map user flash into vector area.
*
* Notes
*   (1) User flash is mapped to addr. 0 after execution of the bootloader.
*       Since we may have halted the boot loader, this may be necessary.
*/
Init() {
  __message "FLASH.mac: Remap USER Flash to addr 0x00"; 
  __writeMemory32(0x01, 0xE01FC040, "Memory");
  __writeMemory32(0x00, 0xFFE10C00, "Memory");  // Disable LCD hardware cursor
  __writeMemory32(0x00, 0xFFE10018, "Memory");  // Disable LCD contoller
}

/*********************************************************************
*
*       execUserPreload()
*
* Function description
*   Called once after the target application is downloaded.
*/
execUserPreload() {
  Init();
}

/*********************************************************************
*
*       execUserReset()
*
* Function description
*   Called each time the reset command is issued. 
*/
execUserReset() {
  Init();
}

/******	EOF *********************************************************/
