/*
  C-file generated by Font converter for emWin V2.16a
  Compiled:    May 29 2002 at 16:54:45

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: PreFont.c
  Font:        Courier New
  Height:      14
*/

#include "GUI.H"

#ifndef GUI_FLASH
  #define GUI_FLASH
#endif

/* The following line needs to be included in any file selecting the
   font. A good place would be GUIConf.H
*/
extern GUI_FLASH const GUI_FONT GUI_FontPreFont;

GUI_FLASH const unsigned char acFontPreFont_0020[ 14] = { /* code 0020 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0021[ 14] = { /* code 0021 */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ___X____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0022[ 14] = { /* code 0022 */
  ________,
  ________,
  ________,
  ________,
  __X_X___,
  __X_X___,
  __X_X___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0023[ 14] = { /* code 0023 */
  ________,
  ________,
  ________,
  ________,
  ___X_X__,
  __X_X___,
  _XXXXX__,
  __X_X___,
  __X_X___,
  _XXXXX__,
  __X_X___,
  _X_X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0024[ 14] = { /* code 0024 */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  __XXX___,
  _X______,
  __XX____,
  ____X___,
  _XXX____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0025[ 14] = { /* code 0025 */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  _X_X____,
  __X_____,
  _XXXX___,
  ___X____,
  __X_X___,
  ___X____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0026[ 14] = { /* code 0026 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  __X_____,
  __X_____,
  _X_XX___,
  _X__X___,
  __XXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0027[ 14] = { /* code 0027 */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0028[ 14] = { /* code 0028 */
  ________,
  ________,
  ________,
  ________,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0029[ 14] = { /* code 0029 */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_002A[ 14] = { /* code 002A */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  _XXXXX__,
  ___X____,
  __X_X___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_002B[ 14] = { /* code 002B */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_002C[ 14] = { /* code 002C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  __XX____,
  __X_____,
  ________};

GUI_FLASH const unsigned char acFontPreFont_002D[ 14] = { /* code 002D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_002E[ 14] = { /* code 002E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_002F[ 14] = { /* code 002F */
  ________,
  ________,
  ________,
  ________,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0030[ 14] = { /* code 0030 */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0031[ 14] = { /* code 0031 */
  ________,
  ________,
  ________,
  ________,
  __XX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0032[ 14] = { /* code 0032 */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0033[ 14] = { /* code 0033 */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _____X__,
  ___XX___,
  _____X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0034[ 14] = { /* code 0034 */
  ________,
  ________,
  ________,
  ________,
  ____X___,
  ___XX___,
  __X_X___,
  _X__X___,
  _XXXXX__,
  ____X___,
  ___XXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0035[ 14] = { /* code 0035 */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  __X_____,
  __X_____,
  __XXX___,
  _____X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0036[ 14] = { /* code 0036 */
  ________,
  ________,
  ________,
  ________,
  ___XXX__,
  __X_____,
  _X______,
  _XXXX___,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0037[ 14] = { /* code 0037 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _X___X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0038[ 14] = { /* code 0038 */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  __XXX___,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0039[ 14] = { /* code 0039 */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  __XXXX__,
  _____X__,
  ____X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_003A[ 14] = { /* code 003A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  ________,
  ________,
  ________,
  __XX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_003B[ 14] = { /* code 003B */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ________,
  ________,
  ___XX___,
  __XX____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_003C[ 14] = { /* code 003C */
  ________,
  ________,
  ________,
  ________,
  ________,
  _____X__,
  ___XX___,
  _XX_____,
  ___XX___,
  _____X__,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_003D[ 14] = { /* code 003D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  ________,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_003E[ 14] = { /* code 003E */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  __XX____,
  ____XX__,
  __XX____,
  _X______,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_003F[ 14] = { /* code 003F */
  ________,
  ________,
  ________,
  ________,
  __XX____,
  _X__X___,
  ____X___,
  ___X____,
  ___X____,
  ________,
  __XX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0040[ 14] = { /* code 0040 */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X__XX__,
  _X_X_X__,
  _X_X_X__,
  _X__XX__,
  _X______,
  __XXXX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0041[ 14] = { /* code 0041 */
  ________,
  ________,
  ________,
  ________,
  __XX____,
  ___X____,
  __X_X___,
  __X_X___,
  __XXX___,
  _X___X__,
  XXX_XXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0042[ 14] = { /* code 0042 */
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X___X__,
  _X___X__,
  XXXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0043[ 14] = { /* code 0043 */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___X__,
  _X______,
  _X______,
  _X______,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0044[ 14] = { /* code 0044 */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  _X__X___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X__X___,
  XXXX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0045[ 14] = { /* code 0045 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  __X__X__,
  __X_X___,
  __XXX___,
  __X_X___,
  __X__X__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0046[ 14] = { /* code 0046 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  __X__X__,
  __X_X___,
  __XXX___,
  __X_X___,
  __X_____,
  _XXX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0047[ 14] = { /* code 0047 */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___X__,
  _X______,
  _X______,
  _X__XXX_,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0048[ 14] = { /* code 0048 */
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  _XXXXX__,
  _X___X__,
  _X___X__,
  XXX_XXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0049[ 14] = { /* code 0049 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_004A[ 14] = { /* code 004A */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  ____X___,
  ____X___,
  ____X___,
  _X__X___,
  _X__X___,
  __XX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_004B[ 14] = { /* code 004B */
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X__X___,
  _XXX____,
  _X__X___,
  _X___X__,
  XXX__XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_004C[ 14] = { /* code 004C */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  __X_____,
  __X_____,
  __X_____,
  __X__X__,
  __X__X__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_004D[ 14] = { /* code 004D */
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _XX_XX__,
  _XX_XX__,
  _X_X_X__,
  _X___X__,
  _X___X__,
  XXX_XXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_004E[ 14] = { /* code 004E */
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _XX__X__,
  _XX__X__,
  _X_X_X__,
  _X_X_X__,
  _X__XX__,
  XXX_XX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_004F[ 14] = { /* code 004F */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0050[ 14] = { /* code 0050 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  __X__X__,
  __X__X__,
  __X__X__,
  __XXX___,
  __X_____,
  _XXX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0051[ 14] = { /* code 0051 */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ___XXX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0052[ 14] = { /* code 0052 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  __X__X__,
  __X__X__,
  __X__X__,
  __XXX___,
  __X__X__,
  _XXX__X_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0053[ 14] = { /* code 0053 */
  ________,
  ________,
  ________,
  ________,
  __XX_X__,
  _X__XX__,
  _X______,
  __XXX___,
  _____X__,
  _X___X__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0054[ 14] = { /* code 0054 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _X_X_X__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0055[ 14] = { /* code 0055 */
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0056[ 14] = { /* code 0056 */
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  _X__X___,
  __X_X___,
  __X_X___,
  __XX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0057[ 14] = { /* code 0057 */
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  __X_X___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0058[ 14] = { /* code 0058 */
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  _X___X__,
  __X_X___,
  ___X____,
  __X_X___,
  _X___X__,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0059[ 14] = { /* code 0059 */
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  __X_X___,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_005A[ 14] = { /* code 005A */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _X___X__,
  ____X___,
  ___X____,
  __X_____,
  _X___X__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_005B[ 14] = { /* code 005B */
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___XX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_005C[ 14] = { /* code 005C */
  ________,
  ________,
  ________,
  ________,
  _X______,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_005D[ 14] = { /* code 005D */
  ________,
  ________,
  ________,
  ________,
  __XX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_005E[ 14] = { /* code 005E */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  __X_X___,
  _X___X__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_005F[ 14] = { /* code 005F */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_};

GUI_FLASH const unsigned char acFontPreFont_0060[ 14] = { /* code 0060 */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  ___X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0061[ 14] = { /* code 0061 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  __XXXX__,
  _X___X__,
  _XXXXXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0062[ 14] = { /* code 0062 */
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  XXXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0063[ 14] = { /* code 0063 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___X__,
  _X______,
  _X______,
  __XXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0064[ 14] = { /* code 0064 */
  ________,
  ________,
  ________,
  ________,
  ____XX__,
  _____X__,
  __XX_X__,
  _X__XX__,
  _X___X__,
  _X___X__,
  __XXXXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0065[ 14] = { /* code 0065 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _XXXXX__,
  _X______,
  __XXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0066[ 14] = { /* code 0066 */
  ________,
  ________,
  ________,
  ________,
  ____XX__,
  ___X____,
  __XXXX__,
  ___X____,
  ___X____,
  ___X____,
  __XXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0067[ 14] = { /* code 0067 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX_XX_,
  _X__XX__,
  _X___X__,
  _X___X__,
  __XXXX__,
  _____X__,
  __XXX___,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0068[ 14] = { /* code 0068 */
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  XXX_XXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0069[ 14] = { /* code 0069 */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ________,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_006A[ 14] = { /* code 006A */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ________,
  _XXXX___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  _XXX____,
  ________};

GUI_FLASH const unsigned char acFontPreFont_006B[ 14] = { /* code 006B */
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X_XXX__,
  _X__X___,
  _XXX____,
  _X__X___,
  XX_XXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_006C[ 14] = { /* code 006C */
  ________,
  ________,
  ________,
  ________,
  __XX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_006D[ 14] = { /* code 006D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_X___,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  XXXXXXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_006E[ 14] = { /* code 006E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  XXX_XXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_006F[ 14] = { /* code 006F */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0070[ 14] = { /* code 0070 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X______,
  XXX_____,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0071[ 14] = { /* code 0071 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX_XX_,
  _X__XX__,
  _X___X__,
  _X___X__,
  __XXXX__,
  _____X__,
  ____XXX_,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0072[ 14] = { /* code 0072 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_XX__,
  __XX____,
  __X_____,
  __X_____,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0073[ 14] = { /* code 0073 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X______,
  __XXX___,
  _____X__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0074[ 14] = { /* code 0074 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  XXXXX___,
  _X______,
  _X______,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0075[ 14] = { /* code 0075 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX__XX__,
  _X___X__,
  _X___X__,
  _X__XX__,
  __XX_XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0076[ 14] = { /* code 0076 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X__X___,
  __X_X___,
  __XX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0077[ 14] = { /* code 0077 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X_X_X__,
  _X_X_X__,
  __X_X___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0078[ 14] = { /* code 0078 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_XX__,
  __X_X___,
  ___X____,
  __X_X___,
  _XX_XX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_0079[ 14] = { /* code 0079 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  _XXX____,
  ________};

GUI_FLASH const unsigned char acFontPreFont_007A[ 14] = { /* code 007A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _X__X___,
  ___X____,
  __X__X__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_007B[ 14] = { /* code 007B */
  ________,
  ________,
  ________,
  ________,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  __XX____,
  ___X____,
  ___X____,
  ___X____,
  ____X___,
  ________};

GUI_FLASH const unsigned char acFontPreFont_007C[ 14] = { /* code 007C */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_007D[ 14] = { /* code 007D */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  ___X____,
  ___X____,
  ___X____,
  ___XX___,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  ________};

GUI_FLASH const unsigned char acFontPreFont_007E[ 14] = { /* code 007E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX_X__,
  _X_XX___,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_007F[ 14] = { /* code 007F */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00A0[ 14] = { /* code 00A0 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00A1[ 14] = { /* code 00A1 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00A2[ 14] = { /* code 00A2 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  __XXX___,
  _X______,
  _X______,
  __XXX___,
  ___X____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00A3[ 14] = { /* code 00A3 */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  __X_____,
  __X_____,
  _XXXX___,
  ___X____,
  __X__X__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00A4[ 14] = { /* code 00A4 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X____X_,
  __XXXX__,
  __X__X__,
  __X__X__,
  __XXXX__,
  _X____X_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00A5[ 14] = { /* code 00A5 */
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  _X___X__,
  __X_X___,
  _XXXXX__,
  ___X____,
  _XXXXX__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00A6[ 14] = { /* code 00A6 */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00A7[ 14] = { /* code 00A7 */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X__X___,
  _XX_____,
  _X_X____,
  __X_X___,
  ___XX___,
  _X__X___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00A8[ 14] = { /* code 00A8 */
  ________,
  ________,
  ________,
  ________,
  _X_X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00A9[ 14] = { /* code 00A9 */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_XXX_X_,
  X_X___X_,
  X_XXX_X_,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00AA[ 14] = { /* code 00AA */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  ____X___,
  __XXX___,
  __XXXX__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00AB[ 14] = { /* code 00AB */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X__X_,
  __X__X__,
  _X__X___,
  __X__X__,
  ___X__X_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00AC[ 14] = { /* code 00AC */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  _____X__,
  _____X__,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00AD[ 14] = { /* code 00AD */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00AE[ 14] = { /* code 00AE */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _XXXXX__,
  X_X_X_X_,
  X_XX__X_,
  XXXXX_X_,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00AF[ 14] = { /* code 00AF */
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00B0[ 14] = { /* code 00B0 */
  ________,
  ________,
  ________,
  __XXX___,
  __X_X___,
  __XXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00B1[ 14] = { /* code 00B1 */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00B2[ 14] = { /* code 00B2 */
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  __X_X___,
  ___X____,
  __XXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00B3[ 14] = { /* code 00B3 */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  ___XX___,
  ____X___,
  __XXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00B4[ 14] = { /* code 00B4 */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  __X_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00B5[ 14] = { /* code 00B5 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX__XX__,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXXXX_,
  _X______,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00B6[ 14] = { /* code 00B6 */
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  X__X_X__,
  X__X_X__,
  _XXX_X__,
  ___X_X__,
  ___X_X__,
  ___X_X__,
  __XX_XX_,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00B7[ 14] = { /* code 00B7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00B8[ 14] = { /* code 00B8 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ____X___,
  __XXX___,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00B9[ 14] = { /* code 00B9 */
  ________,
  ________,
  ________,
  ________,
  __XX____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00BA[ 14] = { /* code 00BA */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  _X_X____,
  __X_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00BB[ 14] = { /* code 00BB */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X__X____,
  _X__X___,
  __X__X__,
  _X__X___,
  X__X____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00BC[ 14] = { /* code 00BC */
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X____X_,
  XXX_XXX_,
  __XX_XX_,
  _X__XXX_,
  _____XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00BD[ 14] = { /* code 00BD */
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X___X__,
  _X__X___,
  XXXXXXX_,
  _X____X_,
  _____X__,
  ____XXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00BE[ 14] = { /* code 00BE */
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  _XX___X_,
  __X__X__,
  XXXXX_X_,
  __X__XX_,
  _X__XXX_,
  _____XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00BF[ 14] = { /* code 00BF */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  ________,
  ________,
  __X_____,
  _X______,
  _X__X___,
  __XX____,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00C0[ 14] = { /* code 00C0 */
  ________,
  __X_____,
  ___X____,
  ________,
  __XX____,
  ___X____,
  __X_X___,
  __X_X___,
  __XXX___,
  _X___X__,
  XXX_XXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00C1[ 14] = { /* code 00C1 */
  ________,
  ____X___,
  ___X____,
  ________,
  __XX____,
  ___X____,
  __X_X___,
  __X_X___,
  __XXX___,
  _X___X__,
  XXX_XXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00C2[ 14] = { /* code 00C2 */
  ________,
  ___X____,
  __X_X___,
  ________,
  __XX____,
  ___X____,
  __X_X___,
  __X_X___,
  __XXX___,
  _X___X__,
  XXX_XXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00C3[ 14] = { /* code 00C3 */
  ________,
  _XX_X___,
  _X_XX___,
  ________,
  __XX____,
  ___X____,
  __X_X___,
  __X_X___,
  __XXX___,
  _X___X__,
  XXX_XXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00C4[ 14] = { /* code 00C4 */
  ________,
  ________,
  __X_X___,
  ________,
  __XX____,
  ___X____,
  __X_X___,
  __X_X___,
  __XXX___,
  _X___X__,
  XXX_XXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00C5[ 14] = { /* code 00C5 */
  __XXX___,
  __X_X___,
  __XXX___,
  ________,
  __XX____,
  ___X____,
  __X_X___,
  __X_X___,
  __XXX___,
  _X___X__,
  XXX_XXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00C6[ 14] = { /* code 00C6 */
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  __X_X_X_,
  __X_X___,
  __XXXX__,
  _X__X___,
  _X__X_X_,
  XXXXXXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00C7[ 14] = { /* code 00C7 */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___X__,
  _X______,
  _X______,
  _X______,
  _X___X__,
  __XXX___,
  ___X____,
  ____X___,
  __XXX___};

GUI_FLASH const unsigned char acFontPreFont_00C8[ 14] = { /* code 00C8 */
  ________,
  __X_____,
  ___X____,
  ________,
  _XXXXX__,
  __X__X__,
  __X_X___,
  __XXX___,
  __X_X___,
  __X__X__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00C9[ 14] = { /* code 00C9 */
  ________,
  ____X___,
  ___X____,
  ________,
  _XXXXX__,
  __X__X__,
  __X_X___,
  __XXX___,
  __X_X___,
  __X__X__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00CA[ 14] = { /* code 00CA */
  ________,
  ___X____,
  __X_X___,
  ________,
  _XXXXX__,
  __X__X__,
  __X_X___,
  __XXX___,
  __X_X___,
  __X__X__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00CB[ 14] = { /* code 00CB */
  ________,
  ________,
  __X_X___,
  ________,
  _XXXXX__,
  __X__X__,
  __X_X___,
  __XXX___,
  __X_X___,
  __X__X__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00CC[ 14] = { /* code 00CC */
  ________,
  __X_____,
  ___X____,
  ________,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00CD[ 14] = { /* code 00CD */
  ________,
  ____X___,
  ___X____,
  ________,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00CE[ 14] = { /* code 00CE */
  ________,
  ___X____,
  __X_X___,
  ________,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00CF[ 14] = { /* code 00CF */
  ________,
  ________,
  __X_X___,
  ________,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00D0[ 14] = { /* code 00D0 */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  _X__X___,
  _X___X__,
  XXX__X__,
  _X___X__,
  _X__X___,
  XXXX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00D1[ 14] = { /* code 00D1 */
  ________,
  __XX_X__,
  __X_XX__,
  ________,
  XXX_XXX_,
  _XX__X__,
  _XX__X__,
  _X_X_X__,
  _X_X_X__,
  _X__XX__,
  XXX_XX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00D2[ 14] = { /* code 00D2 */
  ________,
  __X_____,
  ___X____,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00D3[ 14] = { /* code 00D3 */
  ________,
  ____X___,
  ___X____,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00D4[ 14] = { /* code 00D4 */
  ________,
  ___X____,
  __X_X___,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00D5[ 14] = { /* code 00D5 */
  ________,
  _XX_X___,
  _X_XX___,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00D6[ 14] = { /* code 00D6 */
  ________,
  ________,
  __X_X___,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00D7[ 14] = { /* code 00D7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X__X___,
  __XX____,
  __XX____,
  _X__X___,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00D8[ 14] = { /* code 00D8 */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___X__,
  _X__XX__,
  _X_X_X__,
  _X_X_X__,
  _XX__X__,
  _XXXX___,
  X_______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00D9[ 14] = { /* code 00D9 */
  ________,
  __X_____,
  ___X____,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00DA[ 14] = { /* code 00DA */
  ________,
  ____X___,
  ___X____,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00DB[ 14] = { /* code 00DB */
  ________,
  ___X____,
  __X_X___,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00DC[ 14] = { /* code 00DC */
  ________,
  ________,
  __X_X___,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00DD[ 14] = { /* code 00DD */
  ________,
  ____X___,
  ___X____,
  ________,
  XXX_XXX_,
  _X___X__,
  __X_X___,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00DE[ 14] = { /* code 00DE */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  __X_____,
  __XXX___,
  __X__X__,
  __XXX___,
  __X_____,
  _XXX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00DF[ 14] = { /* code 00DF */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X_XX___,
  _X___X__,
  _X___X__,
  _X_X_X__,
  XXXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00E0[ 14] = { /* code 00E0 */
  ________,
  ________,
  ________,
  __X_____,
  ___X____,
  ________,
  __XXX___,
  _X___X__,
  __XXXX__,
  _X___X__,
  _XXXXXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00E1[ 14] = { /* code 00E1 */
  ________,
  ________,
  ________,
  ____X___,
  ___X____,
  ________,
  __XXX___,
  _X___X__,
  __XXXX__,
  _X___X__,
  _XXXXXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00E2[ 14] = { /* code 00E2 */
  ________,
  ________,
  ________,
  ___X____,
  __X_X___,
  ________,
  __XXX___,
  _X___X__,
  __XXXX__,
  _X___X__,
  _XXXXXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00E3[ 14] = { /* code 00E3 */
  ________,
  ________,
  ________,
  __XX_X__,
  __X_XX__,
  ________,
  __XXX___,
  _X___X__,
  __XXXX__,
  _X___X__,
  _XXXXXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00E4[ 14] = { /* code 00E4 */
  ________,
  ________,
  ________,
  ________,
  __X_X___,
  ________,
  __XXX___,
  _X___X__,
  __XXXX__,
  _X___X__,
  _XXXXXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00E5[ 14] = { /* code 00E5 */
  ________,
  ________,
  __XXX___,
  __X_X___,
  __XXX___,
  ________,
  __XXX___,
  _X___X__,
  __XXXX__,
  _X___X__,
  _XXXXXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00E6[ 14] = { /* code 00E6 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_XX__,
  ___X__X_,
  _XXXXXX_,
  X__X____,
  _XXXXXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00E7[ 14] = { /* code 00E7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___X__,
  _X______,
  _X______,
  __XXXX__,
  ___X____,
  ____X___,
  __XXX___};

GUI_FLASH const unsigned char acFontPreFont_00E8[ 14] = { /* code 00E8 */
  ________,
  ________,
  ________,
  __X_____,
  ___X____,
  ________,
  __XXX___,
  _X___X__,
  _XXXXX__,
  _X______,
  __XXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00E9[ 14] = { /* code 00E9 */
  ________,
  ________,
  ________,
  ____X___,
  ___X____,
  ________,
  __XXX___,
  _X___X__,
  _XXXXX__,
  _X______,
  __XXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00EA[ 14] = { /* code 00EA */
  ________,
  ________,
  ________,
  ___X____,
  __X_X___,
  ________,
  __XXX___,
  _X___X__,
  _XXXXX__,
  _X______,
  __XXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00EB[ 14] = { /* code 00EB */
  ________,
  ________,
  ________,
  ________,
  __X_X___,
  ________,
  __XXX___,
  _X___X__,
  _XXXXX__,
  _X______,
  __XXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00EC[ 14] = { /* code 00EC */
  ________,
  ________,
  ________,
  __X_____,
  ___X____,
  ________,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00ED[ 14] = { /* code 00ED */
  ________,
  ________,
  ________,
  ___X____,
  __X_____,
  ________,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00EE[ 14] = { /* code 00EE */
  ________,
  ________,
  ________,
  ___X____,
  __X_X___,
  ________,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00EF[ 14] = { /* code 00EF */
  ________,
  ________,
  ________,
  ________,
  __X_X___,
  ________,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00F0[ 14] = { /* code 00F0 */
  ________,
  ________,
  ________,
  ________,
  __X_X___,
  __XXX___,
  _____X__,
  __XXXX__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00F1[ 14] = { /* code 00F1 */
  ________,
  ________,
  ________,
  _XX_X___,
  _X_XX___,
  ________,
  XX_XX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  XXX_XXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00F2[ 14] = { /* code 00F2 */
  ________,
  ________,
  ________,
  __X_____,
  ___X____,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00F3[ 14] = { /* code 00F3 */
  ________,
  ________,
  ________,
  ____X___,
  ___X____,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00F4[ 14] = { /* code 00F4 */
  ________,
  ________,
  ________,
  ___X____,
  __X_X___,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00F5[ 14] = { /* code 00F5 */
  ________,
  ________,
  ________,
  __XX_X__,
  __X_XX__,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00F6[ 14] = { /* code 00F6 */
  ________,
  ________,
  ________,
  ________,
  __X_X___,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00F7[ 14] = { /* code 00F7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ________,
  _XXXXX__,
  ________,
  ___X____,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00F8[ 14] = { /* code 00F8 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX_X__,
  _X__X___,
  _X_X_X__,
  __X__X__,
  _X_XX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00F9[ 14] = { /* code 00F9 */
  ________,
  ________,
  ________,
  __X_____,
  ___X____,
  ________,
  XX__XX__,
  _X___X__,
  _X___X__,
  _X__XX__,
  __XX_XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00FA[ 14] = { /* code 00FA */
  ________,
  ________,
  ________,
  ____X___,
  ___X____,
  ________,
  XX__XX__,
  _X___X__,
  _X___X__,
  _X__XX__,
  __XX_XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00FB[ 14] = { /* code 00FB */
  ________,
  ________,
  ________,
  ___X____,
  __X_X___,
  ________,
  XX__XX__,
  _X___X__,
  _X___X__,
  _X__XX__,
  __XX_XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00FC[ 14] = { /* code 00FC */
  ________,
  ________,
  ________,
  ________,
  __X_X___,
  ________,
  XX__XX__,
  _X___X__,
  _X___X__,
  _X__XX__,
  __XX_XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00FD[ 14] = { /* code 00FD */
  ________,
  ________,
  ________,
  ____X___,
  ___X____,
  ________,
  XXX_XXX_,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  _XXX____,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00FE[ 14] = { /* code 00FE */
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X______,
  XXX_____,
  ________};

GUI_FLASH const unsigned char acFontPreFont_00FF[ 14] = { /* code 00FF */
  ________,
  ________,
  ________,
  ________,
  __X_X___,
  ________,
  XXX_XXX_,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  _XXX____,
  ________};

GUI_FLASH const GUI_CHARINFO GUI_FontPreFont_CharInfo[192] = {
   {   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0020 } /* code 0020 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0021 } /* code 0021 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0022 } /* code 0022 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0023 } /* code 0023 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0024 } /* code 0024 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0025 } /* code 0025 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0026 } /* code 0026 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0027 } /* code 0027 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0028 } /* code 0028 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0029 } /* code 0029 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_002A } /* code 002A */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_002B } /* code 002B */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_002C } /* code 002C */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_002D } /* code 002D */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_002E } /* code 002E */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_002F } /* code 002F */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0030 } /* code 0030 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0031 } /* code 0031 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0032 } /* code 0032 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0033 } /* code 0033 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0034 } /* code 0034 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0035 } /* code 0035 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0036 } /* code 0036 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0037 } /* code 0037 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0038 } /* code 0038 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0039 } /* code 0039 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_003A } /* code 003A */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_003B } /* code 003B */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_003C } /* code 003C */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_003D } /* code 003D */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_003E } /* code 003E */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_003F } /* code 003F */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0040 } /* code 0040 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0041 } /* code 0041 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0042 } /* code 0042 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0043 } /* code 0043 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0044 } /* code 0044 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0045 } /* code 0045 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0046 } /* code 0046 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0047 } /* code 0047 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0048 } /* code 0048 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0049 } /* code 0049 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_004A } /* code 004A */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_004B } /* code 004B */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_004C } /* code 004C */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_004D } /* code 004D */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_004E } /* code 004E */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_004F } /* code 004F */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0050 } /* code 0050 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0051 } /* code 0051 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0052 } /* code 0052 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0053 } /* code 0053 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0054 } /* code 0054 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0055 } /* code 0055 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0056 } /* code 0056 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0057 } /* code 0057 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0058 } /* code 0058 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0059 } /* code 0059 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_005A } /* code 005A */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_005B } /* code 005B */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_005C } /* code 005C */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_005D } /* code 005D */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_005E } /* code 005E */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_005F } /* code 005F */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0060 } /* code 0060 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0061 } /* code 0061 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0062 } /* code 0062 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0063 } /* code 0063 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0064 } /* code 0064 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0065 } /* code 0065 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0066 } /* code 0066 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0067 } /* code 0067 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0068 } /* code 0068 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0069 } /* code 0069 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_006A } /* code 006A */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_006B } /* code 006B */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_006C } /* code 006C */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_006D } /* code 006D */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_006E } /* code 006E */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_006F } /* code 006F */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0070 } /* code 0070 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0071 } /* code 0071 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0072 } /* code 0072 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0073 } /* code 0073 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0074 } /* code 0074 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0075 } /* code 0075 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0076 } /* code 0076 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0077 } /* code 0077 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0078 } /* code 0078 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_0079 } /* code 0079 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_007A } /* code 007A */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_007B } /* code 007B */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_007C } /* code 007C */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_007D } /* code 007D */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_007E } /* code 007E */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_007F } /* code 007F */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00A0 } /* code 00A0 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00A1 } /* code 00A1 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00A2 } /* code 00A2 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00A3 } /* code 00A3 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00A4 } /* code 00A4 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00A5 } /* code 00A5 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00A6 } /* code 00A6 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00A7 } /* code 00A7 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00A8 } /* code 00A8 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00A9 } /* code 00A9 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00AA } /* code 00AA */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00AB } /* code 00AB */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00AC } /* code 00AC */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00AD } /* code 00AD */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00AE } /* code 00AE */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00AF } /* code 00AF */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00B0 } /* code 00B0 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00B1 } /* code 00B1 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00B2 } /* code 00B2 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00B3 } /* code 00B3 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00B4 } /* code 00B4 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00B5 } /* code 00B5 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00B6 } /* code 00B6 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00B7 } /* code 00B7 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00B8 } /* code 00B8 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00B9 } /* code 00B9 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00BA } /* code 00BA */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00BB } /* code 00BB */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00BC } /* code 00BC */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00BD } /* code 00BD */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00BE } /* code 00BE */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00BF } /* code 00BF */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00C0 } /* code 00C0 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00C1 } /* code 00C1 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00C2 } /* code 00C2 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00C3 } /* code 00C3 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00C4 } /* code 00C4 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00C5 } /* code 00C5 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00C6 } /* code 00C6 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00C7 } /* code 00C7 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00C8 } /* code 00C8 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00C9 } /* code 00C9 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00CA } /* code 00CA */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00CB } /* code 00CB */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00CC } /* code 00CC */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00CD } /* code 00CD */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00CE } /* code 00CE */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00CF } /* code 00CF */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00D0 } /* code 00D0 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00D1 } /* code 00D1 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00D2 } /* code 00D2 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00D3 } /* code 00D3 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00D4 } /* code 00D4 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00D5 } /* code 00D5 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00D6 } /* code 00D6 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00D7 } /* code 00D7 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00D8 } /* code 00D8 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00D9 } /* code 00D9 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00DA } /* code 00DA */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00DB } /* code 00DB */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00DC } /* code 00DC */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00DD } /* code 00DD */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00DE } /* code 00DE */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00DF } /* code 00DF */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00E0 } /* code 00E0 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00E1 } /* code 00E1 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00E2 } /* code 00E2 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00E3 } /* code 00E3 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00E4 } /* code 00E4 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00E5 } /* code 00E5 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00E6 } /* code 00E6 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00E7 } /* code 00E7 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00E8 } /* code 00E8 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00E9 } /* code 00E9 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00EA } /* code 00EA */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00EB } /* code 00EB */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00EC } /* code 00EC */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00ED } /* code 00ED */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00EE } /* code 00EE */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00EF } /* code 00EF */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00F0 } /* code 00F0 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00F1 } /* code 00F1 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00F2 } /* code 00F2 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00F3 } /* code 00F3 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00F4 } /* code 00F4 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00F5 } /* code 00F5 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00F6 } /* code 00F6 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00F7 } /* code 00F7 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00F8 } /* code 00F8 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00F9 } /* code 00F9 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00FA } /* code 00FA */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00FB } /* code 00FB */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00FC } /* code 00FC */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00FD } /* code 00FD */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00FE } /* code 00FE */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontPreFont_00FF } /* code 00FF */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontPreFont_Prop2 = {
   0x00A0 /* first character */
  ,0x00FF /* last character  */
  ,&GUI_FontPreFont_CharInfo[ 96] /* address of first character */
  ,(void*)0 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontPreFont_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_FontPreFont_CharInfo[  0] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontPreFont_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT GUI_FontPreFont = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,14 /* height of font  */
  ,14 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,(void GUI_FLASH *)&GUI_FontPreFont_Prop1
};

