/*
  C-file generated by Font converter for emWin V2.16a
  Compiled:    May 29 2002 at 16:54:45

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: Sans1bi.c
  Font:        Arial
  Height:      10
*/

#include "GUI.H"

#ifndef GUI_FLASH
  #define GUI_FLASH
#endif

/* The following line needs to be included in any file selecting the
   font. A good place would be GUIConf.H
*/
extern GUI_FLASH const GUI_FONT GUI_FontSans1bi;

GUI_FLASH const unsigned char acFontSans1bi_0020[ 10] = { /* code 0020 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0021[ 10] = { /* code 0021 */
  ________,
  ________,
  __X_____,
  _XX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0022[ 10] = { /* code 0022 */
  ________,
  ________,
  _XXX____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0023[ 10] = { /* code 0023 */
  ________,
  ________,
  _X_X____,
  _X_X____,
  XXXX____,
  _XX_____,
  XXXX____,
  X_X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0024[ 10] = { /* code 0024 */
  ________,
  ________,
  __XX____,
  _XX_X___,
  _XX_____,
  __XX____,
  X_XX____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0025[ 20] = { /* code 0025 */
  ________,________,
  ________,________,
  _XX__X__,________,
  _XX__X__,________,
  _XX_X___,________,
  ___X_XX_,________,
  __X_X_X_,________,
  _X__XXX_,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans1bi_0026[ 10] = { /* code 0026 */
  ________,
  ________,
  __XX____,
  __X_X___,
  __XX____,
  _X_X____,
  _X_XX___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0027[ 10] = { /* code 0027 */
  ________,
  ________,
  _XX_____,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0028[ 10] = { /* code 0028 */
  ________,
  ________,
  __X_____,
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_FLASH const unsigned char acFontSans1bi_0029[ 10] = { /* code 0029 */
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_002A[ 10] = { /* code 002A */
  ________,
  ________,
  __X_____,
  _XXX____,
  _X_X____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_002B[ 10] = { /* code 002B */
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  XXXX____,
  __X_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_002C[ 10] = { /* code 002C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_______,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_002D[ 10] = { /* code 002D */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_002E[ 10] = { /* code 002E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_002F[ 10] = { /* code 002F */
  ________,
  ________,
  __X_____,
  __X_____,
  _X______,
  _X______,
  X_______,
  X_______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0030[ 10] = { /* code 0030 */
  ________,
  ________,
  __XX____,
  _X_XX___,
  _X_XX___,
  _X_X____,
  _X_X____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0031[ 10] = { /* code 0031 */
  ________,
  ________,
  ___X____,
  __XX____,
  _XXX____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0032[ 10] = { /* code 0032 */
  ________,
  ________,
  __XX____,
  _X_XX___,
  ___X____,
  __XX____,
  _XX_____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0033[ 10] = { /* code 0033 */
  ________,
  ________,
  __XX____,
  _X_X____,
  ___X____,
  __XX____,
  XX_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0034[ 10] = { /* code 0034 */
  ________,
  ________,
  ___X____,
  __XX____,
  __XX____,
  _X_X____,
  XXXX____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0035[ 10] = { /* code 0035 */
  ________,
  ________,
  __XXX___,
  _X______,
  _XXX____,
  ___X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0036[ 10] = { /* code 0036 */
  ________,
  ________,
  __XX____,
  _X__X___,
  _XXX____,
  _X_X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0037[ 10] = { /* code 0037 */
  ________,
  ________,
  _XXXX___,
  ___X____,
  __XX____,
  __X_____,
  _XX_____,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0038[ 10] = { /* code 0038 */
  ________,
  ________,
  __XX____,
  _X_XX___,
  _XXX____,
  _X_X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0039[ 10] = { /* code 0039 */
  ________,
  ________,
  __XX____,
  _X_X____,
  _X_X____,
  _XXX____,
  ___X____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_003A[ 10] = { /* code 003A */
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_003B[ 10] = { /* code 003B */
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  _X______,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_003C[ 10] = { /* code 003C */
  ________,
  ________,
  ________,
  ___X____,
  _XX_____,
  XX______,
  __XX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_003D[ 10] = { /* code 003D */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  ________,
  XXXX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_003E[ 10] = { /* code 003E */
  ________,
  ________,
  ________,
  XX______,
  _XXX____,
  __XX____,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_003F[ 10] = { /* code 003F */
  ________,
  ________,
  __XX____,
  _X__X___,
  ___XX___,
  __X_____,
  __X_____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0040[ 20] = { /* code 0040 */
  ________,________,
  ________,________,
  __XXXX__,________,
  _X____X_,________,
  X_XXXXX_,________,
  X_X__X_X,________,
  X_X_X_X_,________,
  X_XXXX__,________,
  _X____X_,________,
  __XXXX__,________};

GUI_FLASH const unsigned char acFontSans1bi_0041[ 10] = { /* code 0041 */
  ________,
  ________,
  ___X____,
  __XXX___,
  __X_X___,
  _X__X___,
  _XXXX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0042[ 10] = { /* code 0042 */
  ________,
  ________,
  _XXXX___,
  _X__XX__,
  _X__X___,
  _XXXX___,
  _X__X___,
  XXXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0043[ 10] = { /* code 0043 */
  ________,
  ________,
  __XXX___,
  _XX__X__,
  _X______,
  _X______,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0044[ 10] = { /* code 0044 */
  ________,
  ________,
  _XXXX___,
  _X__XX__,
  _X___X__,
  _X__XX__,
  _X__X___,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0045[ 10] = { /* code 0045 */
  ________,
  ________,
  _XXXXX__,
  _X______,
  _X______,
  _XXX____,
  _X______,
  XXXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0046[ 10] = { /* code 0046 */
  ________,
  ________,
  _XXXX___,
  _X______,
  _X______,
  _XXXX___,
  _X______,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0047[ 10] = { /* code 0047 */
  ________,
  ________,
  __XXX___,
  _XX__X__,
  _X______,
  _X_XXX__,
  _X___X__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0048[ 10] = { /* code 0048 */
  ________,
  ________,
  _XX__X__,
  _X___X__,
  _XXXXX__,
  _X__X___,
  _X__X___,
  XX__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0049[ 10] = { /* code 0049 */
  ________,
  ________,
  _XX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_004A[ 10] = { /* code 004A */
  ________,
  ________,
  ____X___,
  ___XX___,
  ___X____,
  ___X____,
  X__X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_004B[ 10] = { /* code 004B */
  ________,
  ________,
  _XX__X__,
  _X_XX___,
  _XXX____,
  _XXX____,
  _X__X___,
  XX__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_004C[ 10] = { /* code 004C */
  ________,
  ________,
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  XXXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_004D[ 20] = { /* code 004D */
  ________,________,
  ________,________,
  _XX__XX_,________,
  _XX__XX_,________,
  _XX_X_X_,________,
  _XX_XX__,________,
  _XXX_X__,________,
  X_XX_X__,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans1bi_004E[ 10] = { /* code 004E */
  ________,
  ________,
  __X__X__,
  _XX__X__,
  _XXX_X__,
  _X_XX___,
  _X_XX___,
  XX__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_004F[ 10] = { /* code 004F */
  ________,
  ________,
  __XXX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0050[ 10] = { /* code 0050 */
  ________,
  ________,
  _XXXX___,
  _X__XX__,
  _X__X___,
  _XXXX___,
  _X______,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0051[ 10] = { /* code 0051 */
  ________,
  ________,
  __XXX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  _X_XXX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0052[ 10] = { /* code 0052 */
  ________,
  ________,
  _XXXX___,
  _X___X__,
  _X__XX__,
  _XXXX___,
  _X__X___,
  XX__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0053[ 10] = { /* code 0053 */
  ________,
  ________,
  __XXX___,
  _X__X___,
  _XX_____,
  ___XX___,
  _X__X___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0054[ 10] = { /* code 0054 */
  ________,
  ________,
  _XXXXX__,
  ___X____,
  __XX____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0055[ 10] = { /* code 0055 */
  ________,
  ________,
  _XX__X__,
  _X___X__,
  _X__XX__,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0056[ 10] = { /* code 0056 */
  ________,
  ________,
  _X___X__,
  _X___X__,
  _X__X___,
  _XXXX___,
  __XX____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0057[ 20] = { /* code 0057 */
  ________,________,
  ________,________,
  _X__X__X,________,
  _X__X__X,________,
  _X_XX_X_,________,
  _X_XX_X_,________,
  _XX__XX_,________,
  _XX__X__,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans1bi_0058[ 10] = { /* code 0058 */
  ________,
  ________,
  _X___X__,
  _XX_X___,
  __XX____,
  __XX____,
  _XXX____,
  XX_XX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0059[ 10] = { /* code 0059 */
  ________,
  ________,
  _X___X__,
  _XX_X___,
  __XXX___,
  __XX____,
  __XX____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_005A[ 10] = { /* code 005A */
  ________,
  ________,
  _XXXX___,
  ___XX___,
  ___X____,
  __X_____,
  _X______,
  XXXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_005B[ 10] = { /* code 005B */
  ________,
  ________,
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______,
  XX______};

GUI_FLASH const unsigned char acFontSans1bi_005C[ 10] = { /* code 005C */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_005D[ 10] = { /* code 005D */
  ________,
  ________,
  _XX_____,
  __X_____,
  _XX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______};

GUI_FLASH const unsigned char acFontSans1bi_005E[ 10] = { /* code 005E */
  ________,
  ________,
  __X_____,
  _XX_____,
  _X_X____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_005F[ 10] = { /* code 005F */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____};

GUI_FLASH const unsigned char acFontSans1bi_0060[ 10] = { /* code 0060 */
  ________,
  ________,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0061[ 10] = { /* code 0061 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  __XX____,
  XX_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0062[ 10] = { /* code 0062 */
  ________,
  ________,
  _XX_____,
  _X______,
  _XXXX___,
  _X__X___,
  _X__X___,
  X_XX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0063[ 10] = { /* code 0063 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _X______,
  XX_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0064[ 10] = { /* code 0064 */
  ________,
  ________,
  ____X___,
  ____X___,
  _XXXX___,
  _X_XX___,
  XX_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0065[ 10] = { /* code 0065 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _X_X____,
  XXX_____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0066[ 10] = { /* code 0066 */
  ________,
  ________,
  __XX____,
  _X______,
  _XX_____,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0067[ 10] = { /* code 0067 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _X_XX___,
  XX_X____,
  _XXX____,
  X__X____,
  _XX_____};

GUI_FLASH const unsigned char acFontSans1bi_0068[ 10] = { /* code 0068 */
  ________,
  ________,
  _XX_____,
  _X______,
  _XXXX___,
  _X__X___,
  _X_X____,
  XX_X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0069[ 10] = { /* code 0069 */
  ________,
  ________,
  _XX_____,
  ________,
  _X______,
  _X______,
  _X______,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_006A[ 10] = { /* code 006A */
  ________,
  ________,
  _XX_____,
  ________,
  _X______,
  _X______,
  _X______,
  XX______,
  X_______,
  X_______};

GUI_FLASH const unsigned char acFontSans1bi_006B[ 10] = { /* code 006B */
  ________,
  ________,
  _XX_____,
  _X______,
  _X_X____,
  _XX_____,
  _X_X____,
  XX_X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_006C[ 10] = { /* code 006C */
  ________,
  ________,
  _XX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_006D[ 20] = { /* code 006D */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXX_,________,
  _X_X__X_,________,
  _X_X__X_,________,
  XX_X_X__,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans1bi_006E[ 10] = { /* code 006E */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _X__X___,
  _X_X____,
  XX_X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_006F[ 10] = { /* code 006F */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _X__X___,
  XX_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0070[ 10] = { /* code 0070 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _X__X___,
  _X__X___,
  XXXX____,
  X_______,
  X_______};

GUI_FLASH const unsigned char acFontSans1bi_0071[ 10] = { /* code 0071 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _X_XX___,
  XX_X____,
  _XXX____,
  ___X____,
  ___X____};

GUI_FLASH const unsigned char acFontSans1bi_0072[ 10] = { /* code 0072 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _X______,
  _X______,
  X_______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0073[ 10] = { /* code 0073 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _XX_____,
  ___X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0074[ 10] = { /* code 0074 */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0075[ 10] = { /* code 0075 */
  ________,
  ________,
  ________,
  ________,
  _X__X___,
  _X_XX___,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0076[ 10] = { /* code 0076 */
  ________,
  ________,
  ________,
  ________,
  _X_XX___,
  _X_X____,
  _XX_____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0077[ 10] = { /* code 0077 */
  ________,
  ________,
  ________,
  ________,
  _X_X_X__,
  _XXX_X__,
  _XXXX___,
  _X__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0078[ 10] = { /* code 0078 */
  ________,
  ________,
  ________,
  ________,
  _X_X____,
  __X_____,
  _XX_____,
  XX_X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_0079[ 10] = { /* code 0079 */
  ________,
  ________,
  ________,
  ________,
  _X_XX___,
  _X_X____,
  _XX_____,
  _XX_____,
  _X______,
  XX______};

GUI_FLASH const unsigned char acFontSans1bi_007A[ 10] = { /* code 007A */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  __X_____,
  _X______,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_007B[ 10] = { /* code 007B */
  ________,
  ________,
  __XX____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_FLASH const unsigned char acFontSans1bi_007C[ 10] = { /* code 007C */
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_FLASH const unsigned char acFontSans1bi_007D[ 10] = { /* code 007D */
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _XX_____,
  _X______,
  _X______,
  X_______,
  X_______};

GUI_FLASH const unsigned char acFontSans1bi_007E[ 10] = { /* code 007E */
  ________,
  ________,
  ________,
  ________,
  _X______,
  X_XX____,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_007F[ 10] = { /* code 007F */
  ________,
  ________,
  ________,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00A0[ 10] = { /* code 00A0 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00A1[ 10] = { /* code 00A1 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______,
  X_______};

GUI_FLASH const unsigned char acFontSans1bi_00A2[ 10] = { /* code 00A2 */
  ________,
  ________,
  ________,
  ___X____,
  _XXX____,
  _XX_____,
  XX_X____,
  _XXX____,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00A3[ 10] = { /* code 00A3 */
  ________,
  ________,
  __XX____,
  _X__X___,
  _X______,
  _XX_____,
  _X______,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00A4[ 10] = { /* code 00A4 */
  ________,
  ________,
  ________,
  X_XX____,
  _X_X____,
  _X_X____,
  XXXX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00A5[ 10] = { /* code 00A5 */
  ________,
  ________,
  _X__X___,
  _X_X____,
  __XX____,
  XXXX____,
  XXXX____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00A6[ 10] = { /* code 00A6 */
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  ________,
  ________,
  _X______,
  _X______,
  _X______};

GUI_FLASH const unsigned char acFontSans1bi_00A7[ 10] = { /* code 00A7 */
  ________,
  ________,
  __XX____,
  _X_X____,
  _XX_____,
  _X_X____,
  _X_X____,
  __X_____,
  X__X____,
  _XX_____};

GUI_FLASH const unsigned char acFontSans1bi_00A8[ 10] = { /* code 00A8 */
  ________,
  ________,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00A9[ 10] = { /* code 00A9 */
  ________,
  ________,
  __XX____,
  XXX_X___,
  XX_X_X__,
  XX___X__,
  X_XX_X__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00AA[ 10] = { /* code 00AA */
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00AB[ 10] = { /* code 00AB */
  ________,
  ________,
  ________,
  ________,
  __XX____,
  _XX_____,
  _XX_____,
  _X_X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00AC[ 10] = { /* code 00AC */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00AD[ 10] = { /* code 00AD */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00AE[ 10] = { /* code 00AE */
  ________,
  ________,
  __XX____,
  XX__X___,
  XXXX_X__,
  XX_X_X__,
  XX_X_X__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00AF[ 10] = { /* code 00AF */
  ________,
  _XXXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00B0[ 10] = { /* code 00B0 */
  ________,
  ________,
  __X_____,
  _X_X____,
  __X_____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00B1[ 10] = { /* code 00B1 */
  ________,
  ________,
  ________,
  __X_____,
  XXXX____,
  __X_____,
  __X_____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00B2[ 10] = { /* code 00B2 */
  ________,
  ________,
  _XX_____,
  __X_____,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00B3[ 10] = { /* code 00B3 */
  ________,
  ________,
  _XX_____,
  __X_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00B4[ 10] = { /* code 00B4 */
  ________,
  ________,
  __X_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00B5[ 10] = { /* code 00B5 */
  ________,
  ________,
  ________,
  ________,
  _X_XX___,
  _X_X____,
  XX_X____,
  XXXX____,
  X_______,
  X_______};

GUI_FLASH const unsigned char acFontSans1bi_00B6[ 10] = { /* code 00B6 */
  ________,
  ________,
  _XXX____,
  XX_X____,
  XX_X____,
  _X_X____,
  _X_X____,
  _X_X____,
  _X_X____,
  ___X____};

GUI_FLASH const unsigned char acFontSans1bi_00B7[ 10] = { /* code 00B7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00B8[ 10] = { /* code 00B8 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  X_______};

GUI_FLASH const unsigned char acFontSans1bi_00B9[ 10] = { /* code 00B9 */
  ________,
  ________,
  __X_____,
  _XX_____,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00BA[ 10] = { /* code 00BA */
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00BB[ 10] = { /* code 00BB */
  ________,
  ________,
  ________,
  ________,
  _X_X____,
  _X_X____,
  _XXX____,
  X_X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00BC[ 20] = { /* code 00BC */
  ________,________,
  ________,________,
  __X__X__,________,
  _XX__X__,________,
  _X__X___,________,
  ___X__X_,________,
  __X_XX__,________,
  _X__XX__,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans1bi_00BD[ 20] = { /* code 00BD */
  ________,________,
  ________,________,
  __X__X__,________,
  _XX_X___,________,
  _X__X___,________,
  ___X_X__,________,
  __X_X_X_,________,
  _X__XX__,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans1bi_00BE[ 20] = { /* code 00BE */
  ________,________,
  ________,________,
  _XX___X_,________,
  __X__X__,________,
  __X_X___,________,
  _X_X__X_,________,
  __X_XX__,________,
  _X__XX__,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans1bi_00BF[ 10] = { /* code 00BF */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  __X_____,
  _XX_____,
  XX______,
  X__X____,
  _XX_____};

GUI_FLASH const unsigned char acFontSans1bi_00C0[ 10] = { /* code 00C0 */
  ________,
  ___X____,
  ___X____,
  __XXX___,
  __X_X___,
  _X__X___,
  _XXXX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00C1[ 10] = { /* code 00C1 */
  ________,
  ____X___,
  ___X____,
  __XXX___,
  __X_X___,
  _X__X___,
  _XXXX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00C2[ 10] = { /* code 00C2 */
  ________,
  ___XX___,
  ___X____,
  __XXX___,
  __X_X___,
  _X__X___,
  _XXXX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00C3[ 10] = { /* code 00C3 */
  ________,
  ___X____,
  ___XX___,
  __XXX___,
  __X_X___,
  _X__X___,
  _XXXX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00C4[ 10] = { /* code 00C4 */
  ________,
  ___XX___,
  ___X____,
  __XXX___,
  __X_X___,
  _X__X___,
  _XXXX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00C5[ 10] = { /* code 00C5 */
  ________,
  ___XX___,
  ___X____,
  __XXX___,
  __X_X___,
  _X__X___,
  _XXXX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00C6[ 20] = { /* code 00C6 */
  ________,________,
  ________,________,
  ___XXXXX,________,
  __XXX___,________,
  __X_X___,________,
  _X__XXXX,________,
  _XXXX___,________,
  X__XXXXX,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans1bi_00C7[ 10] = { /* code 00C7 */
  ________,
  ________,
  __XXX___,
  _XX__X__,
  _X______,
  _X______,
  _X__XX__,
  _XXXX___,
  ___X____,
  __X_____};

GUI_FLASH const unsigned char acFontSans1bi_00C8[ 10] = { /* code 00C8 */
  ________,
  ___X____,
  _XXXXX__,
  _X______,
  _X______,
  _XXX____,
  _X______,
  XXXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00C9[ 10] = { /* code 00C9 */
  ________,
  ____X___,
  _XXXXX__,
  _X______,
  _X______,
  _XXX____,
  _X______,
  XXXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00CA[ 10] = { /* code 00CA */
  ________,
  ___XX___,
  _XXXXX__,
  _X______,
  _X______,
  _XXX____,
  _X______,
  XXXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00CB[ 10] = { /* code 00CB */
  ________,
  ___XX___,
  _XXXXX__,
  _X______,
  _X______,
  _XXX____,
  _X______,
  XXXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00CC[ 10] = { /* code 00CC */
  ________,
  _X______,
  _XX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00CD[ 10] = { /* code 00CD */
  ________,
  __X_____,
  _XX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00CE[ 10] = { /* code 00CE */
  ________,
  _XX_____,
  _XX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00CF[ 10] = { /* code 00CF */
  ________,
  _XX_____,
  _XX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00D0[ 10] = { /* code 00D0 */
  ________,
  ________,
  __XXX___,
  _X__XX__,
  _X___X__,
  XX__XX__,
  _X__X___,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00D1[ 10] = { /* code 00D1 */
  ________,
  ___X____,
  __X_XX__,
  _XX__X__,
  _XXX_X__,
  _X_XX___,
  _X_XX___,
  XX__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00D2[ 10] = { /* code 00D2 */
  ________,
  ___X____,
  __XXX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00D3[ 10] = { /* code 00D3 */
  ________,
  ____X___,
  __XXX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00D4[ 10] = { /* code 00D4 */
  ________,
  ___XX___,
  __XXX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00D5[ 10] = { /* code 00D5 */
  ________,
  ___X____,
  __XXX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00D6[ 10] = { /* code 00D6 */
  ________,
  ___XX___,
  __XXX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00D7[ 10] = { /* code 00D7 */
  ________,
  ________,
  ________,
  ___X____,
  _XXX____,
  _XX_____,
  _X_X____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00D8[ 10] = { /* code 00D8 */
  ________,
  ________,
  __XXXX__,
  _XX_XX__,
  _X_X_X__,
  _X_X_X__,
  _XX_XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00D9[ 10] = { /* code 00D9 */
  ________,
  ___X____,
  _XX_XX__,
  _X___X__,
  _X__XX__,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00DA[ 10] = { /* code 00DA */
  ________,
  ____X___,
  _XXX_X__,
  _X___X__,
  _X__XX__,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00DB[ 10] = { /* code 00DB */
  ________,
  ___XX___,
  _XX__X__,
  _X___X__,
  _X__XX__,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00DC[ 10] = { /* code 00DC */
  ________,
  ___XX___,
  _XX__X__,
  _X___X__,
  _X__XX__,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00DD[ 10] = { /* code 00DD */
  ________,
  ____X___,
  _X___X__,
  _XX_X___,
  __XXX___,
  __XX____,
  __XX____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00DE[ 10] = { /* code 00DE */
  ________,
  ________,
  _XX_____,
  _XXXX___,
  _X__X___,
  _X__X___,
  _XXXX___,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00DF[ 10] = { /* code 00DF */
  ________,
  ________,
  __XX____,
  _X_XX___,
  _X_X____,
  _X_X____,
  _X__X___,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00E0[ 10] = { /* code 00E0 */
  ________,
  ________,
  __X_____,
  ________,
  _XXX____,
  __XX____,
  XX_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00E1[ 10] = { /* code 00E1 */
  ________,
  ________,
  ___X____,
  ________,
  _XXX____,
  __XX____,
  XX_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00E2[ 10] = { /* code 00E2 */
  ________,
  ________,
  __XX____,
  ________,
  _XXX____,
  __XX____,
  XX_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00E3[ 10] = { /* code 00E3 */
  ________,
  ________,
  __X_____,
  ___X____,
  _XXX____,
  __XX____,
  XX_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00E4[ 10] = { /* code 00E4 */
  ________,
  ________,
  __XX____,
  ________,
  _XXX____,
  __XX____,
  XX_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00E5[ 10] = { /* code 00E5 */
  ________,
  ________,
  __XX____,
  ________,
  _XXX____,
  __XX____,
  XX_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00E6[ 20] = { /* code 00E6 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXX_,________,
  __XX__X_,________,
  XX_XXX__,________,
  XXXXXX__,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans1bi_00E7[ 10] = { /* code 00E7 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _X______,
  XX_X____,
  _XXX____,
  __X_____,
  _X______};

GUI_FLASH const unsigned char acFontSans1bi_00E8[ 10] = { /* code 00E8 */
  ________,
  ________,
  __X_____,
  ________,
  _XXX____,
  _X_X____,
  XXX_____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00E9[ 10] = { /* code 00E9 */
  ________,
  ________,
  ___X____,
  ________,
  _XXX____,
  _X_X____,
  XXX_____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00EA[ 10] = { /* code 00EA */
  ________,
  ________,
  __XX____,
  ________,
  _XXX____,
  _X_X____,
  XXX_____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00EB[ 10] = { /* code 00EB */
  ________,
  ________,
  __XX____,
  ________,
  _XXX____,
  _X_X____,
  XXX_____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00EC[ 10] = { /* code 00EC */
  ________,
  ________,
  _X______,
  ________,
  _X______,
  _X______,
  _X______,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00ED[ 10] = { /* code 00ED */
  ________,
  ________,
  __X_____,
  ________,
  _X______,
  _X______,
  _X______,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00EE[ 10] = { /* code 00EE */
  ________,
  ________,
  _XX_____,
  ________,
  _X______,
  _X______,
  _X______,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00EF[ 10] = { /* code 00EF */
  ________,
  ________,
  _XX_____,
  ________,
  _X______,
  _X______,
  _X______,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00F0[ 10] = { /* code 00F0 */
  ________,
  ________,
  ___XX___,
  __XX____,
  _XXXX___,
  _X__X___,
  XX_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00F1[ 10] = { /* code 00F1 */
  ________,
  ________,
  __X_____,
  ___X____,
  _XXXX___,
  _X__X___,
  _X_X____,
  XX_X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00F2[ 10] = { /* code 00F2 */
  ________,
  ________,
  __X_____,
  ________,
  _XXX____,
  _X__X___,
  XX_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00F3[ 10] = { /* code 00F3 */
  ________,
  ________,
  ___X____,
  ________,
  _XXX____,
  _X__X___,
  XX_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00F4[ 10] = { /* code 00F4 */
  ________,
  ________,
  __XX____,
  ________,
  _XXX____,
  _X__X___,
  XX_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00F5[ 10] = { /* code 00F5 */
  ________,
  ________,
  __X_____,
  ___X____,
  _XXX____,
  _X__X___,
  XX_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00F6[ 10] = { /* code 00F6 */
  ________,
  ________,
  __XX____,
  ________,
  _XXX____,
  _X__X___,
  XX_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00F7[ 10] = { /* code 00F7 */
  ________,
  ________,
  ________,
  __X_____,
  ________,
  XXXX____,
  __X_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00F8[ 10] = { /* code 00F8 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _XX_X___,
  XXXXX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00F9[ 10] = { /* code 00F9 */
  ________,
  ________,
  __X_____,
  ________,
  _X__X___,
  _X_XX___,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00FA[ 10] = { /* code 00FA */
  ________,
  ________,
  ___X____,
  ________,
  _X__X___,
  _X_XX___,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00FB[ 10] = { /* code 00FB */
  ________,
  ________,
  __XX____,
  ________,
  _X__X___,
  _X_XX___,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00FC[ 10] = { /* code 00FC */
  ________,
  ________,
  __XX____,
  ________,
  _X__X___,
  _X_XX___,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1bi_00FD[ 10] = { /* code 00FD */
  ________,
  ________,
  ___X____,
  ________,
  _X_XX___,
  _X_X____,
  _XX_____,
  _XX_____,
  _X______,
  XX______};

GUI_FLASH const unsigned char acFontSans1bi_00FE[ 10] = { /* code 00FE */
  ________,
  ________,
  _XX_____,
  _X______,
  _XXXX___,
  _X__X___,
  _X__X___,
  X_XX____,
  X_______,
  X_______};

GUI_FLASH const unsigned char acFontSans1bi_00FF[ 10] = { /* code 00FF */
  ________,
  ________,
  __XX____,
  ________,
  _X_XX___,
  _X_X____,
  _XX_____,
  _XX_____,
  _X______,
  XX______};

GUI_FLASH const GUI_CHARINFO GUI_FontSans1bi_CharInfo[192] = {
   {   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_0020 } /* code 0020 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_0021 } /* code 0021 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0022 } /* code 0022 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0023 } /* code 0023 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0024 } /* code 0024 */
  ,{   9,   7,  2, (void GUI_FLASH *)&acFontSans1bi_0025 } /* code 0025 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_0026 } /* code 0026 */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_0027 } /* code 0027 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_0028 } /* code 0028 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_0029 } /* code 0029 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_002A } /* code 002A */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_002B } /* code 002B */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_002C } /* code 002C */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_002D } /* code 002D */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_002E } /* code 002E */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_002F } /* code 002F */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0030 } /* code 0030 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0031 } /* code 0031 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0032 } /* code 0032 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0033 } /* code 0033 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0034 } /* code 0034 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0035 } /* code 0035 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0036 } /* code 0036 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0037 } /* code 0037 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0038 } /* code 0038 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0039 } /* code 0039 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_003A } /* code 003A */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_003B } /* code 003B */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_003C } /* code 003C */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_003D } /* code 003D */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_003E } /* code 003E */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_003F } /* code 003F */
  ,{  10,   8,  2, (void GUI_FLASH *)&acFontSans1bi_0040 } /* code 0040 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_0041 } /* code 0041 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_0042 } /* code 0042 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_0043 } /* code 0043 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_0044 } /* code 0044 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_0045 } /* code 0045 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_0046 } /* code 0046 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_0047 } /* code 0047 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_0048 } /* code 0048 */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_0049 } /* code 0049 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_004A } /* code 004A */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_004B } /* code 004B */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_004C } /* code 004C */
  ,{   9,   7,  2, (void GUI_FLASH *)&acFontSans1bi_004D } /* code 004D */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_004E } /* code 004E */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_004F } /* code 004F */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_0050 } /* code 0050 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_0051 } /* code 0051 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_0052 } /* code 0052 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_0053 } /* code 0053 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_0054 } /* code 0054 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_0055 } /* code 0055 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_0056 } /* code 0056 */
  ,{  10,   8,  2, (void GUI_FLASH *)&acFontSans1bi_0057 } /* code 0057 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_0058 } /* code 0058 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_0059 } /* code 0059 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_005A } /* code 005A */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_005B } /* code 005B */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_005C } /* code 005C */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_005D } /* code 005D */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_005E } /* code 005E */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_005F } /* code 005F */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_0060 } /* code 0060 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0061 } /* code 0061 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_0062 } /* code 0062 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0063 } /* code 0063 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_0064 } /* code 0064 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0065 } /* code 0065 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_0066 } /* code 0066 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_0067 } /* code 0067 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_0068 } /* code 0068 */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_0069 } /* code 0069 */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_006A } /* code 006A */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_006B } /* code 006B */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_006C } /* code 006C */
  ,{   9,   7,  2, (void GUI_FLASH *)&acFontSans1bi_006D } /* code 006D */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_006E } /* code 006E */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_006F } /* code 006F */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_0070 } /* code 0070 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_0071 } /* code 0071 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_0072 } /* code 0072 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0073 } /* code 0073 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_0074 } /* code 0074 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_0075 } /* code 0075 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0076 } /* code 0076 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_0077 } /* code 0077 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0078 } /* code 0078 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_0079 } /* code 0079 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_007A } /* code 007A */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_007B } /* code 007B */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_007C } /* code 007C */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_007D } /* code 007D */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_007E } /* code 007E */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_007F } /* code 007F */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_00A0 } /* code 00A0 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_00A1 } /* code 00A1 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00A2 } /* code 00A2 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00A3 } /* code 00A3 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00A4 } /* code 00A4 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00A5 } /* code 00A5 */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_00A6 } /* code 00A6 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00A7 } /* code 00A7 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_00A8 } /* code 00A8 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00A9 } /* code 00A9 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_00AA } /* code 00AA */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00AB } /* code 00AB */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00AC } /* code 00AC */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_00AD } /* code 00AD */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00AE } /* code 00AE */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00AF } /* code 00AF */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_00B0 } /* code 00B0 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00B1 } /* code 00B1 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_00B2 } /* code 00B2 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_00B3 } /* code 00B3 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_00B4 } /* code 00B4 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00B5 } /* code 00B5 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00B6 } /* code 00B6 */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_00B7 } /* code 00B7 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_00B8 } /* code 00B8 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_00B9 } /* code 00B9 */
  ,{   5,   3,  1, (void GUI_FLASH *)&acFontSans1bi_00BA } /* code 00BA */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00BB } /* code 00BB */
  ,{   9,   7,  2, (void GUI_FLASH *)&acFontSans1bi_00BC } /* code 00BC */
  ,{   9,   7,  2, (void GUI_FLASH *)&acFontSans1bi_00BD } /* code 00BD */
  ,{   9,   7,  2, (void GUI_FLASH *)&acFontSans1bi_00BE } /* code 00BE */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00BF } /* code 00BF */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00C0 } /* code 00C0 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00C1 } /* code 00C1 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00C2 } /* code 00C2 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00C3 } /* code 00C3 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00C4 } /* code 00C4 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00C5 } /* code 00C5 */
  ,{  10,   8,  2, (void GUI_FLASH *)&acFontSans1bi_00C6 } /* code 00C6 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00C7 } /* code 00C7 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00C8 } /* code 00C8 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00C9 } /* code 00C9 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00CA } /* code 00CA */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00CB } /* code 00CB */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_00CC } /* code 00CC */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_00CD } /* code 00CD */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_00CE } /* code 00CE */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_00CF } /* code 00CF */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00D0 } /* code 00D0 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00D1 } /* code 00D1 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00D2 } /* code 00D2 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00D3 } /* code 00D3 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00D4 } /* code 00D4 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00D5 } /* code 00D5 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00D6 } /* code 00D6 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00D7 } /* code 00D7 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00D8 } /* code 00D8 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00D9 } /* code 00D9 */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00DA } /* code 00DA */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00DB } /* code 00DB */
  ,{   8,   6,  1, (void GUI_FLASH *)&acFontSans1bi_00DC } /* code 00DC */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00DD } /* code 00DD */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00DE } /* code 00DE */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00DF } /* code 00DF */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00E0 } /* code 00E0 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00E1 } /* code 00E1 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00E2 } /* code 00E2 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00E3 } /* code 00E3 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00E4 } /* code 00E4 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00E5 } /* code 00E5 */
  ,{   9,   7,  2, (void GUI_FLASH *)&acFontSans1bi_00E6 } /* code 00E6 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00E7 } /* code 00E7 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00E8 } /* code 00E8 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00E9 } /* code 00E9 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00EA } /* code 00EA */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00EB } /* code 00EB */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_00EC } /* code 00EC */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_00ED } /* code 00ED */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_00EE } /* code 00EE */
  ,{   4,   2,  1, (void GUI_FLASH *)&acFontSans1bi_00EF } /* code 00EF */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00F0 } /* code 00F0 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00F1 } /* code 00F1 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00F2 } /* code 00F2 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00F3 } /* code 00F3 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00F4 } /* code 00F4 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00F5 } /* code 00F5 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00F6 } /* code 00F6 */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00F7 } /* code 00F7 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00F8 } /* code 00F8 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00F9 } /* code 00F9 */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00FA } /* code 00FA */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00FB } /* code 00FB */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00FC } /* code 00FC */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00FD } /* code 00FD */
  ,{   7,   5,  1, (void GUI_FLASH *)&acFontSans1bi_00FE } /* code 00FE */
  ,{   6,   4,  1, (void GUI_FLASH *)&acFontSans1bi_00FF } /* code 00FF */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSans1bi_Prop2 = {
   0x00A0 /* first character */
  ,0x00FF /* last character  */
  ,&GUI_FontSans1bi_CharInfo[ 96] /* address of first character */
  ,(void*)0 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSans1bi_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_FontSans1bi_CharInfo[  0] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSans1bi_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT GUI_FontSans1bi = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,10 /* height of font  */
  ,10 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,(void GUI_FLASH *)&GUI_FontSans1bi_Prop1
};

