/*
  C-file generated by Font converter for emWin V2.16a
  Compiled:    May 29 2002 at 16:54:45

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: Sans2b.c
  Font:        Arial
  Height:      15
*/

#include "GUI.H"

#ifndef GUI_FLASH
  #define GUI_FLASH
#endif

/* The following line needs to be included in any file selecting the
   font. A good place would be GUIConf.H
*/
extern GUI_FLASH const GUI_FONT GUI_FontSans2b;

GUI_FLASH const unsigned char acFontSans2b_0020[ 15] = { /* code 0020 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0021[ 15] = { /* code 0021 */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0022[ 15] = { /* code 0022 */
  ________,
  ________,
  ________,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0023[ 15] = { /* code 0023 */
  ________,
  ________,
  ________,
  __X__X__,
  __X__X__,
  XXXXXX__,
  _X__X___,
  _X__X___,
  XXXXXX__,
  _X__X___,
  X__X____,
  X__X____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0024[ 15] = { /* code 0024 */
  ________,
  ________,
  ___X____,
  __XXX___,
  _X_X_X__,
  _X_X____,
  _XXX____,
  __XXX___,
  ___XXX__,
  ___X_X__,
  _X_X_X__,
  __XXX___,
  ___X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0025[ 30] = { /* code 0025 */
  ________,________,
  ________,________,
  ________,________,
  XXX__X__,________,
  X_X__X__,________,
  X_X_X___,________,
  X_X_X___,________,
  XXX_XXXX,________,
  ___X_X_X,________,
  ___X_X_X,________,
  __X__X_X,________,
  __X__XXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_0026[ 30] = { /* code 0026 */
  ________,________,
  ________,________,
  ________,________,
  __XXX___,________,
  _XX_XX__,________,
  _XX_XX__,________,
  __XXX___,________,
  _XXXX___,________,
  XX_XX_XX,________,
  XX__XXX_,________,
  XX__XXXX,________,
  _XXXX_XX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_0027[ 15] = { /* code 0027 */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0028[ 15] = { /* code 0028 */
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  _X______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _X______,
  _XX_____,
  __X_____,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0029[ 15] = { /* code 0029 */
  ________,
  ________,
  ________,
  X_______,
  XX______,
  _X______,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _X______,
  XX______,
  X_______,
  ________};

GUI_FLASH const unsigned char acFontSans2b_002A[ 15] = { /* code 002A */
  ________,
  ________,
  ________,
  __X_____,
  _XXX____,
  __X_____,
  _X_X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_002B[ 15] = { /* code 002B */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  XXXXXX__,
  __XX____,
  __XX____,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_002C[ 15] = { /* code 002C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  _X______,
  X_______,
  ________};

GUI_FLASH const unsigned char acFontSans2b_002D[ 15] = { /* code 002D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_002E[ 15] = { /* code 002E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_002F[ 15] = { /* code 002F */
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______,
  X_______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0030[ 15] = { /* code 0030 */
  ________,
  ________,
  ________,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0031[ 15] = { /* code 0031 */
  ________,
  ________,
  ________,
  ___XX___,
  __XXX___,
  _XXXX___,
  _X_XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0032[ 15] = { /* code 0032 */
  ________,
  ________,
  ________,
  _XXXX___,
  XX__XX__,
  ____XX__,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XX______,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0033[ 15] = { /* code 0033 */
  ________,
  ________,
  ________,
  _XXXX___,
  XX__XX__,
  ____XX__,
  __XXX___,
  ____XX__,
  ____XX__,
  ____XX__,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0034[ 15] = { /* code 0034 */
  ________,
  ________,
  ________,
  ___XX___,
  __XXX___,
  __XXX___,
  _X_XX___,
  _X_XX___,
  X__XX___,
  XXXXXX__,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0035[ 15] = { /* code 0035 */
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX_____,
  XX______,
  XXXXX___,
  XX__XX__,
  ____XX__,
  ____XX__,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0036[ 15] = { /* code 0036 */
  ________,
  ________,
  ________,
  __XXX___,
  _X__XX__,
  XX______,
  XXXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0037[ 15] = { /* code 0037 */
  ________,
  ________,
  ________,
  XXXXXX__,
  ____XX__,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0038[ 15] = { /* code 0038 */
  ________,
  ________,
  ________,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0039[ 15] = { /* code 0039 */
  ________,
  ________,
  ________,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__,
  ____XX__,
  XX__X___,
  _XXX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_003A[ 15] = { /* code 003A */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_003B[ 15] = { /* code 003B */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  _X______,
  X_______,
  ________};

GUI_FLASH const unsigned char acFontSans2b_003C[ 15] = { /* code 003C */
  ________,
  ________,
  ________,
  ________,
  _____X__,
  ___XXX__,
  _XXX____,
  XX______,
  _XXX____,
  ___XXX__,
  _____X__,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_003D[ 15] = { /* code 003D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  ________,
  XXXXXX__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_003E[ 15] = { /* code 003E */
  ________,
  ________,
  ________,
  ________,
  X_______,
  XXX_____,
  __XXX___,
  ____XX__,
  __XXX___,
  XXX_____,
  X_______,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_003F[ 15] = { /* code 003F */
  ________,
  ________,
  ________,
  _XXXX___,
  XX__XX__,
  ____XX__,
  ___XX___,
  __XX____,
  __XX____,
  ________,
  __XX____,
  __XX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0040[ 30] = { /* code 0040 */
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __XX____,XX______,
  _X__XX_X,XXX_____,
  _X_XXXXX,X_X_____,
  X_XX__XX,__X_____,
  X_XX__XX,__X_____,
  X_XX__XX,__X_____,
  X_XXXXXX,_X______,
  X__XX_XX,X_______,
  _X______,__X_____,
  __X_____,_X______,
  ___XXXXX,X_______};

GUI_FLASH const unsigned char acFontSans2b_0041[ 15] = { /* code 0041 */
  ________,
  ________,
  ________,
  __XXX___,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XXXXXXX_,
  XX___XX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0042[ 15] = { /* code 0042 */
  ________,
  ________,
  ________,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0043[ 15] = { /* code 0043 */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0044[ 15] = { /* code 0044 */
  ________,
  ________,
  ________,
  XXXXX___,
  XX__XX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX__XX__,
  XXXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0045[ 15] = { /* code 0045 */
  ________,
  ________,
  ________,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0046[ 15] = { /* code 0046 */
  ________,
  ________,
  ________,
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0047[ 15] = { /* code 0047 */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  XX______,
  XX______,
  XX__XXX_,
  XX___XX_,
  XX___XX_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0048[ 15] = { /* code 0048 */
  ________,
  ________,
  ________,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXXX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0049[ 15] = { /* code 0049 */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_004A[ 15] = { /* code 004A */
  ________,
  ________,
  ________,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_004B[ 15] = { /* code 004B */
  ________,
  ________,
  ________,
  XX___XX_,
  XX__XX__,
  XX_XX___,
  XXXXX___,
  XXXXXX__,
  XX__XX__,
  XX__XX__,
  XX___XX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_004C[ 15] = { /* code 004C */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_004D[ 30] = { /* code 004D */
  ________,________,
  ________,________,
  ________,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXXX_XXX,X_______,
  XXXX_XXX,X_______,
  XX_X_X_X,X_______,
  XX_X_X_X,X_______,
  XX_XXX_X,X_______,
  XX_XXX_X,X_______,
  XX__X__X,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_004E[ 15] = { /* code 004E */
  ________,
  ________,
  ________,
  XX___XX_,
  XXX__XX_,
  XXX__XX_,
  XXXX_XX_,
  XX_X_XX_,
  XX_XXXX_,
  XX__XXX_,
  XX__XXX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_004F[ 30] = { /* code 004F */
  ________,________,
  ________,________,
  ________,________,
  __XXXX__,________,
  _XX__XX_,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  _XX__XX_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_0050[ 15] = { /* code 0050 */
  ________,
  ________,
  ________,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0051[ 30] = { /* code 0051 */
  ________,________,
  ________,________,
  ________,________,
  __XXXX__,________,
  _XX__XX_,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX__X_XX,________,
  _XX__XX_,________,
  __XXXXX_,________,
  _______X,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_0052[ 15] = { /* code 0052 */
  ________,
  ________,
  ________,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XX__XX__,
  XX___XX_,
  XX___XX_,
  XX____XX,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0053[ 15] = { /* code 0053 */
  ________,
  ________,
  ________,
  _XXXXX__,
  XX___XX_,
  XX______,
  XXXX____,
  _XXXXX__,
  ___XXXX_,
  _____XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0054[ 15] = { /* code 0054 */
  ________,
  ________,
  ________,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0055[ 15] = { /* code 0055 */
  ________,
  ________,
  ________,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0056[ 15] = { /* code 0056 */
  ________,
  ________,
  ________,
  X_____XX,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  __XXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0057[ 30] = { /* code 0057 */
  ________,________,
  ________,________,
  ________,________,
  X___XXX_,__XX____,
  X___XXX_,__XX____,
  XX_XXXXX,_XX_____,
  XX_XX_XX,_XX_____,
  XX_XX_XX,_XX_____,
  XX_XX_XX,_XX_____,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_0058[ 15] = { /* code 0058 */
  ________,
  ________,
  ________,
  XX___XX_,
  XX___XX_,
  _XX_XX__,
  _XXXXX__,
  __XXX___,
  _XXXXX__,
  _XX_XX__,
  XX___XX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0059[ 15] = { /* code 0059 */
  ________,
  ________,
  ________,
  X____XX_,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_005A[ 15] = { /* code 005A */
  ________,
  ________,
  ________,
  XXXXXX__,
  ____XX__,
  ___XX___,
  __XX____,
  __XX____,
  _XX_____,
  XX______,
  XX______,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_005B[ 15] = { /* code 005B */
  ________,
  ________,
  ________,
  XXX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXX_____,
  ________};

GUI_FLASH const unsigned char acFontSans2b_005C[ 15] = { /* code 005C */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  __X_____,
  __X_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_005D[ 15] = { /* code 005D */
  ________,
  ________,
  ________,
  XXX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXX_____,
  ________};

GUI_FLASH const unsigned char acFontSans2b_005E[ 15] = { /* code 005E */
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  _XXXX___,
  _X__X___,
  XX__XX__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_005F[ 15] = { /* code 005F */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0060[ 15] = { /* code 0060 */
  ________,
  ________,
  ________,
  XX______,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0061[ 15] = { /* code 0061 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  X___XX__,
  __XXXX__,
  _XX_XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0062[ 15] = { /* code 0062 */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX_XX___,
  XXX_XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XXX_XX__,
  XX_XX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0063[ 15] = { /* code 0063 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  XX__XX__,
  XX______,
  XX______,
  XX______,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0064[ 15] = { /* code 0064 */
  ________,
  ________,
  ________,
  ____XX__,
  ____XX__,
  _XX_XX__,
  XX_XXX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX_XXX__,
  _XX_XX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0065[ 15] = { /* code 0065 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XXXXXX__,
  XX______,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0066[ 15] = { /* code 0066 */
  ________,
  ________,
  ________,
  _XXX____,
  XX______,
  XXX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0067[ 15] = { /* code 0067 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_XX__,
  XX_XXX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX_XXX__,
  _XX_XX__,
  X___XX__,
  _XXXX___,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0068[ 15] = { /* code 0068 */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX_XX___,
  XXX_XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0069[ 15] = { /* code 0069 */
  ________,
  ________,
  ________,
  XX______,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_006A[ 15] = { /* code 006A */
  ________,
  ________,
  ________,
  XX______,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  X_______,
  ________};

GUI_FLASH const unsigned char acFontSans2b_006B[ 15] = { /* code 006B */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX__XX__,
  XX_XX___,
  XXXX____,
  XXXXX___,
  XX_XX___,
  XX__XX__,
  XX__XX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_006C[ 15] = { /* code 006C */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_006D[ 30] = { /* code 006D */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX_XXX_X,X_______,
  XXX_XXX_,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_006E[ 15] = { /* code 006E */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX___,
  XXX_XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_006F[ 15] = { /* code 006F */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0070[ 15] = { /* code 0070 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX___,
  XXX_XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XXX_XX__,
  XX_XX___,
  XX______,
  XX______,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0071[ 15] = { /* code 0071 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_XX__,
  XX_XXX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX_XXX__,
  _XX_XX__,
  ____XX__,
  ____XX__,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0072[ 15] = { /* code 0072 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0073[ 15] = { /* code 0073 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  XX__XX__,
  XXX_____,
  _XXXX___,
  ___XXX__,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0074[ 15] = { /* code 0074 */
  ________,
  ________,
  ________,
  _X______,
  XX______,
  XXX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _XX_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0075[ 15] = { /* code 0075 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX_XXX__,
  _XX_XX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0076[ 15] = { /* code 0076 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X___XX__,
  X___XX__,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0077[ 30] = { /* code 0077 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX__X__X,X_______,
  XX_XXX_X,X_______,
  XX_XXX_X,X_______,
  XX_X_X_X,X_______,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XX___XX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_0078[ 15] = { /* code 0078 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  __XX____,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_0079[ 15] = { /* code 0079 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X___XX__,
  X___XX__,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  _XXX____,
  _XXX____,
  _XX_____,
  XX______,
  ________};

GUI_FLASH const unsigned char acFontSans2b_007A[ 15] = { /* code 007A */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  ___XX___,
  __XX____,
  _XX_____,
  _XX_____,
  XX______,
  XXXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_007B[ 15] = { /* code 007B */
  ________,
  ________,
  ________,
  __XXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XXX___,
  ________};

GUI_FLASH const unsigned char acFontSans2b_007C[ 15] = { /* code 007C */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontSans2b_007D[ 15] = { /* code 007D */
  ________,
  ________,
  ________,
  XX______,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______,
  ________};

GUI_FLASH const unsigned char acFontSans2b_007E[ 15] = { /* code 007E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX__X__,
  X__XX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_007F[ 30] = { /* code 007F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _XXXXXXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_00A0[ 15] = { /* code 00A0 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00A1[ 15] = { /* code 00A1 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00A2[ 15] = { /* code 00A2 */
  ________,
  ________,
  ________,
  ____X___,
  ___X____,
  _XXXX___,
  XX_XXX__,
  XX_X____,
  XX_X____,
  XXX_____,
  XXX__X__,
  _XXXX___,
  _X______,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00A3[ 15] = { /* code 00A3 */
  ________,
  ________,
  ________,
  __XXX___,
  _XX_XX__,
  _XX_____,
  _XX_____,
  XXXXXX__,
  __XX____,
  _XXX____,
  XXXXX_X_,
  _X__XXX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00A4[ 15] = { /* code 00A4 */
  ________,
  ________,
  ________,
  ________,
  X___X___,
  XXXXXX__,
  X___X___,
  X___X___,
  X___X___,
  XXXXXX__,
  X___X___,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00A5[ 15] = { /* code 00A5 */
  ________,
  ________,
  ________,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  _XXXX___,
  XXXXXX__,
  __XX____,
  XXXXXX__,
  __XX____,
  __XX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00A6[ 15] = { /* code 00A6 */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00A7[ 15] = { /* code 00A7 */
  ________,
  ________,
  ________,
  __XXX___,
  _XX_XX__,
  _XX_____,
  _XXX____,
  XXXXX___,
  XX_XXX__,
  XXX_XX__,
  _XXXX___,
  __XXX___,
  ___XX___,
  XX_XX___,
  _XXX____};

GUI_FLASH const unsigned char acFontSans2b_00A8[ 15] = { /* code 00A8 */
  ________,
  ________,
  ________,
  X__X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00A9[ 30] = { /* code 00A9 */
  ________,________,
  ________,________,
  ________,________,
  __XXXXX_,________,
  _X_____X,________,
  X__XXX__,X_______,
  X_X___X_,X_______,
  X_X_____,X_______,
  X_X___X_,X_______,
  X__XXX__,X_______,
  _X_____X,________,
  __XXXXX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_00AA[ 15] = { /* code 00AA */
  ________,
  ________,
  ________,
  XXX_____,
  _XX_____,
  X_X_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00AB[ 15] = { /* code 00AB */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __X__X__,
  _XX_XX__,
  XX_XX___,
  _XX_XX__,
  __X__X__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00AC[ 15] = { /* code 00AC */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00AD[ 15] = { /* code 00AD */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00AE[ 30] = { /* code 00AE */
  ________,________,
  ________,________,
  ________,________,
  __XXXXX_,________,
  _X_____X,________,
  X__XXX__,X_______,
  X__X__X_,X_______,
  X__XXX__,X_______,
  X__X_X__,X_______,
  X__X__X_,X_______,
  _X_____X,________,
  __XXXXX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_00AF[ 15] = { /* code 00AF */
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00B0[ 15] = { /* code 00B0 */
  ________,
  ________,
  ________,
  _XX_____,
  X__X____,
  X__X____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00B1[ 15] = { /* code 00B1 */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  XXXXXX__,
  __XX____,
  __XX____,
  ________,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00B2[ 15] = { /* code 00B2 */
  ________,
  ________,
  ________,
  XXX_____,
  __X_____,
  _X______,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00B3[ 15] = { /* code 00B3 */
  ________,
  ________,
  ________,
  XXX_____,
  _X______,
  __X_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00B4[ 15] = { /* code 00B4 */
  ________,
  ________,
  ________,
  __XX____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00B5[ 15] = { /* code 00B5 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XXXXXX__,
  XX______,
  XX______,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00B6[ 15] = { /* code 00B6 */
  ________,
  ________,
  ________,
  _XXXXX__,
  XXX_X___,
  XXX_X___,
  XXX_X___,
  _XX_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00B7[ 15] = { /* code 00B7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00B8[ 15] = { /* code 00B8 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  __X_____,
  XX______};

GUI_FLASH const unsigned char acFontSans2b_00B9[ 15] = { /* code 00B9 */
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  __X_____,
  __X_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00BA[ 15] = { /* code 00BA */
  ________,
  ________,
  ________,
  XXX_____,
  X_X_____,
  X_X_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00BB[ 15] = { /* code 00BB */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X__X____,
  XX_XX___,
  _XX_XX__,
  XX_XX___,
  X__X____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00BC[ 30] = { /* code 00BC */
  ________,________,
  ________,________,
  ________,________,
  _X____X_,________,
  XX____X_,________,
  _X___X__,________,
  _X___X__,________,
  ____X___,________,
  ___X____,X_______,
  ___X___X,X_______,
  __X___XX,XX______,
  _X______,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_00BD[ 30] = { /* code 00BD */
  ________,________,
  ________,________,
  ________,________,
  _X____X_,________,
  XX____X_,________,
  _X___X__,________,
  _X__X___,________,
  ____X___,________,
  ___X__XX,X_______,
  ___X____,X_______,
  __X____X,________,
  _X____XX,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_00BE[ 30] = { /* code 00BE */
  ________,________,
  ________,________,
  ________,________,
  XXX____X,________,
  _X____X_,________,
  __X___X_,________,
  XXX__X__,________,
  ____X___,________,
  ____X___,X_______,
  ___X___X,X_______,
  ___X__XX,XX______,
  __X_____,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_00BF[ 15] = { /* code 00BF */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  ________,
  __XX____,
  __XX____,
  _XX_____,
  XX______,
  XX__XX__,
  _XXXX___,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00C0[ 15] = { /* code 00C0 */
  __XX____,
  ___XX___,
  ________,
  __XXX___,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XXXXXXX_,
  XX___XX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00C1[ 15] = { /* code 00C1 */
  ____XX__,
  ___XX___,
  ________,
  __XXX___,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XXXXXXX_,
  XX___XX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00C2[ 15] = { /* code 00C2 */
  ___X____,
  __X_X___,
  ________,
  __XXX___,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XXXXXXX_,
  XX___XX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00C3[ 15] = { /* code 00C3 */
  __XX_X__,
  __X_XX__,
  ________,
  __XXX___,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XXXXXXX_,
  XX___XX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00C4[ 15] = { /* code 00C4 */
  ________,
  __X__X__,
  ________,
  __XXX___,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XXXXXXX_,
  XX___XX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00C5[ 15] = { /* code 00C5 */
  ___XX___,
  __X__X__,
  __X__X__,
  __XXX___,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XXXXXXX_,
  XX___XX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00C6[ 30] = { /* code 00C6 */
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,XXXX____,
  ___XX_XX,________,
  ___XX_XX,________,
  __XX__XX,________,
  __XX__XX,XXXX____,
  __XX__XX,________,
  _XXXXXXX,________,
  _XX___XX,________,
  XX____XX,XXXX____,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_00C7[ 15] = { /* code 00C7 */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _XX__XX_,
  __XXXX__,
  ___XX___,
  ____X___,
  __XX____};

GUI_FLASH const unsigned char acFontSans2b_00C8[ 15] = { /* code 00C8 */
  _XX_____,
  __XX____,
  ________,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00C9[ 15] = { /* code 00C9 */
  ___XX___,
  __XX____,
  ________,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00CA[ 15] = { /* code 00CA */
  ___X____,
  __X_X___,
  ________,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00CB[ 15] = { /* code 00CB */
  ________,
  _X__X___,
  ________,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00CC[ 15] = { /* code 00CC */
  X_______,
  XX______,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00CD[ 15] = { /* code 00CD */
  _XX_____,
  XX______,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00CE[ 15] = { /* code 00CE */
  _X______,
  X_X_____,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00CF[ 15] = { /* code 00CF */
  ________,
  __X_____,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00D0[ 30] = { /* code 00D0 */
  ________,________,
  ________,________,
  ________,________,
  _XXXXX__,________,
  _XX__XX_,________,
  _XX___XX,________,
  _XX___XX,________,
  XXXXX_XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX__XX_,________,
  _XXXXX__,________,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_00D1[ 15] = { /* code 00D1 */
  __XX_X__,
  __X_XX__,
  ________,
  XX___XX_,
  XXX__XX_,
  XXX__XX_,
  XXXX_XX_,
  XX_X_XX_,
  XX_XXXX_,
  XX__XXX_,
  XX__XXX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00D2[ 30] = { /* code 00D2 */
  __XX____,________,
  ___XX___,________,
  ________,________,
  __XXXX__,________,
  _XX__XX_,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  _XX__XX_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_00D3[ 30] = { /* code 00D3 */
  ____XX__,________,
  ___XX___,________,
  ________,________,
  __XXXX__,________,
  _XX__XX_,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  _XX__XX_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_00D4[ 30] = { /* code 00D4 */
  ____X___,________,
  ___X_X__,________,
  ________,________,
  __XXXX__,________,
  _XX__XX_,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  _XX__XX_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_00D5[ 30] = { /* code 00D5 */
  __XX_X__,________,
  __X_XX__,________,
  ________,________,
  __XXXX__,________,
  _XX__XX_,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  _XX__XX_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_00D6[ 30] = { /* code 00D6 */
  ________,________,
  __X__X__,________,
  ________,________,
  __XXXX__,________,
  _XX__XX_,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  _XX__XX_,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_00D7[ 15] = { /* code 00D7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X__X___,
  _XXXX___,
  __XX____,
  _XXXX___,
  _X__X___,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00D8[ 30] = { /* code 00D8 */
  ________,________,
  ________,________,
  _______X,________,
  __XXXX_X,X_______,
  _XX__XXX,________,
  XX___XXX,________,
  XX__XXXX,________,
  XX_XX_XX,________,
  XXXX__XX,________,
  XXX___XX,________,
  XXX__XX_,________,
  X_XXXX__,________,
  X_______,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_00D9[ 15] = { /* code 00D9 */
  __XX____,
  ___XX___,
  ________,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00DA[ 15] = { /* code 00DA */
  ___XX___,
  __XX____,
  ________,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00DB[ 15] = { /* code 00DB */
  ___X____,
  __X_X___,
  ________,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00DC[ 15] = { /* code 00DC */
  ________,
  __X__X__,
  ________,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00DD[ 15] = { /* code 00DD */
  ___XX___,
  __XX____,
  ________,
  X____XX_,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00DE[ 15] = { /* code 00DE */
  ________,
  ________,
  ________,
  XX______,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00DF[ 15] = { /* code 00DF */
  ________,
  ________,
  ________,
  _XXX____,
  XX_XX___,
  XX_XX___,
  XXXX____,
  XXXX____,
  XX_XX___,
  XX__XX__,
  XX__XX__,
  XX_XX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00E0[ 15] = { /* code 00E0 */
  ________,
  ________,
  _XX_____,
  __XX____,
  ________,
  _XXXX___,
  X___XX__,
  __XXXX__,
  _XX_XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00E1[ 15] = { /* code 00E1 */
  ________,
  ________,
  ___XX___,
  __XX____,
  ________,
  _XXXX___,
  X___XX__,
  __XXXX__,
  _XX_XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00E2[ 15] = { /* code 00E2 */
  ________,
  ________,
  ___X____,
  __X_X___,
  ________,
  _XXXX___,
  X___XX__,
  __XXXX__,
  _XX_XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00E3[ 15] = { /* code 00E3 */
  ________,
  ________,
  _XX_X___,
  _X_XX___,
  ________,
  _XXXX___,
  X___XX__,
  __XXXX__,
  _XX_XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00E4[ 15] = { /* code 00E4 */
  ________,
  ________,
  ________,
  _X__X___,
  ________,
  _XXXX___,
  X___XX__,
  __XXXX__,
  _XX_XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00E5[ 15] = { /* code 00E5 */
  __XX____,
  _X__X___,
  _X__X___,
  __XX____,
  ________,
  _XXXX___,
  X___XX__,
  __XXXX__,
  _XX_XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00E6[ 30] = { /* code 00E6 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXX_XX,X_______,
  X___XX__,XX______,
  __XXXX__,XX______,
  _XX_XXXX,XX______,
  XX__XX__,________,
  XX__XX__,XX______,
  _XXX_XXX,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans2b_00E7[ 15] = { /* code 00E7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  XX__XX__,
  XX______,
  XX______,
  XX______,
  XX__XX__,
  _XXXX___,
  __XX____,
  ___X____,
  _XX_____};

GUI_FLASH const unsigned char acFontSans2b_00E8[ 15] = { /* code 00E8 */
  ________,
  ________,
  _XX_____,
  __XX____,
  ________,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XXXXXX__,
  XX______,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00E9[ 15] = { /* code 00E9 */
  ________,
  ________,
  ___XX___,
  __XX____,
  ________,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XXXXXX__,
  XX______,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00EA[ 15] = { /* code 00EA */
  ________,
  ________,
  ___X____,
  __X_X___,
  ________,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XXXXXX__,
  XX______,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00EB[ 15] = { /* code 00EB */
  ________,
  ________,
  ________,
  _X__X___,
  ________,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XXXXXX__,
  XX______,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00EC[ 15] = { /* code 00EC */
  ________,
  ________,
  X_______,
  XX______,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00ED[ 15] = { /* code 00ED */
  ________,
  ________,
  _XX_____,
  XX______,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00EE[ 15] = { /* code 00EE */
  ________,
  ________,
  _X______,
  X_X_____,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00EF[ 15] = { /* code 00EF */
  ________,
  ________,
  ________,
  __X_____,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00F0[ 15] = { /* code 00F0 */
  ________,
  ________,
  ________,
  __X_X___,
  ___X____,
  __X_X___,
  _XXXXX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00F1[ 15] = { /* code 00F1 */
  ________,
  ________,
  _XX_X___,
  _X_XX___,
  ________,
  XX_XX___,
  XXX_XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00F2[ 15] = { /* code 00F2 */
  ________,
  ________,
  __XX____,
  ___XX___,
  ________,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00F3[ 15] = { /* code 00F3 */
  ________,
  ________,
  ___XX___,
  __XX____,
  ________,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00F4[ 15] = { /* code 00F4 */
  ________,
  ________,
  ___X____,
  __X_X___,
  ________,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00F5[ 15] = { /* code 00F5 */
  ________,
  ________,
  _XX_X___,
  _X_XX___,
  ________,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00F6[ 15] = { /* code 00F6 */
  ________,
  ________,
  ________,
  _X__X___,
  ________,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00F7[ 15] = { /* code 00F7 */
  ________,
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  ________,
  XXXXXX__,
  ________,
  __XX____,
  __XX____,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00F8[ 15] = { /* code 00F8 */
  ________,
  ________,
  ________,
  ________,
  ____X___,
  _XXXXX__,
  XX_XX___,
  XX_XXX__,
  XXXXXX__,
  XXX_XX__,
  _XX_XX__,
  XXXXX___,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00F9[ 15] = { /* code 00F9 */
  ________,
  ________,
  _XX_____,
  __XX____,
  ________,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX_XXX__,
  _XX_XX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00FA[ 15] = { /* code 00FA */
  ________,
  ________,
  ___XX___,
  __XX____,
  ________,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX_XXX__,
  _XX_XX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00FB[ 15] = { /* code 00FB */
  ________,
  ________,
  ___X____,
  __X_X___,
  ________,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX_XXX__,
  _XX_XX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00FC[ 15] = { /* code 00FC */
  ________,
  ________,
  ________,
  _X__X___,
  ________,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX_XXX__,
  _XX_XX__,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00FD[ 15] = { /* code 00FD */
  ________,
  ________,
  ___XX___,
  __XX____,
  ________,
  X___XX__,
  X___XX__,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  _XXX____,
  _XXX____,
  _XX_____,
  XX______,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00FE[ 15] = { /* code 00FE */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XXXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XXXXX___,
  XX______,
  XX______,
  ________};

GUI_FLASH const unsigned char acFontSans2b_00FF[ 15] = { /* code 00FF */
  ________,
  ________,
  ________,
  _X__X___,
  ________,
  X___XX__,
  X___XX__,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  _XXX____,
  _XXX____,
  _XX_____,
  XX______,
  ________};

GUI_FLASH const GUI_CHARINFO GUI_FontSans2b_CharInfo[192] = {
   {   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_0020 } /* code 0020 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_0021 } /* code 0021 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans2b_0022 } /* code 0022 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0023 } /* code 0023 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0024 } /* code 0024 */
  ,{   9,   9,  2, (void GUI_FLASH *)&acFontSans2b_0025 } /* code 0025 */
  ,{   9,   9,  2, (void GUI_FLASH *)&acFontSans2b_0026 } /* code 0026 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_0027 } /* code 0027 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_0028 } /* code 0028 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_0029 } /* code 0029 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans2b_002A } /* code 002A */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_002B } /* code 002B */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_002C } /* code 002C */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_002D } /* code 002D */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_002E } /* code 002E */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_002F } /* code 002F */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0030 } /* code 0030 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0031 } /* code 0031 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0032 } /* code 0032 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0033 } /* code 0033 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0034 } /* code 0034 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0035 } /* code 0035 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0036 } /* code 0036 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0037 } /* code 0037 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0038 } /* code 0038 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0039 } /* code 0039 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_003A } /* code 003A */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_003B } /* code 003B */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_003C } /* code 003C */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_003D } /* code 003D */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_003E } /* code 003E */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_003F } /* code 003F */
  ,{  12,  12,  2, (void GUI_FLASH *)&acFontSans2b_0040 } /* code 0040 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_0041 } /* code 0041 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_0042 } /* code 0042 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_0043 } /* code 0043 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_0044 } /* code 0044 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0045 } /* code 0045 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans2b_0046 } /* code 0046 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_0047 } /* code 0047 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_0048 } /* code 0048 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_0049 } /* code 0049 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_004A } /* code 004A */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_004B } /* code 004B */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_004C } /* code 004C */
  ,{  10,  10,  2, (void GUI_FLASH *)&acFontSans2b_004D } /* code 004D */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_004E } /* code 004E */
  ,{   9,   9,  2, (void GUI_FLASH *)&acFontSans2b_004F } /* code 004F */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_0050 } /* code 0050 */
  ,{   9,   9,  2, (void GUI_FLASH *)&acFontSans2b_0051 } /* code 0051 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_0052 } /* code 0052 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_0053 } /* code 0053 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0054 } /* code 0054 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_0055 } /* code 0055 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_0056 } /* code 0056 */
  ,{  12,  12,  2, (void GUI_FLASH *)&acFontSans2b_0057 } /* code 0057 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_0058 } /* code 0058 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0059 } /* code 0059 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_005A } /* code 005A */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_005B } /* code 005B */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_005C } /* code 005C */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_005D } /* code 005D */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_005E } /* code 005E */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_005F } /* code 005F */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_0060 } /* code 0060 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0061 } /* code 0061 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0062 } /* code 0062 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0063 } /* code 0063 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0064 } /* code 0064 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0065 } /* code 0065 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_0066 } /* code 0066 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0067 } /* code 0067 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0068 } /* code 0068 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_0069 } /* code 0069 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_006A } /* code 006A */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_006B } /* code 006B */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_006C } /* code 006C */
  ,{  11,  11,  2, (void GUI_FLASH *)&acFontSans2b_006D } /* code 006D */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_006E } /* code 006E */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_006F } /* code 006F */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0070 } /* code 0070 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0071 } /* code 0071 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans2b_0072 } /* code 0072 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0073 } /* code 0073 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_0074 } /* code 0074 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0075 } /* code 0075 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans2b_0076 } /* code 0076 */
  ,{  10,  10,  2, (void GUI_FLASH *)&acFontSans2b_0077 } /* code 0077 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_0078 } /* code 0078 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans2b_0079 } /* code 0079 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans2b_007A } /* code 007A */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans2b_007B } /* code 007B */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_007C } /* code 007C */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans2b_007D } /* code 007D */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_007E } /* code 007E */
  ,{   9,   9,  2, (void GUI_FLASH *)&acFontSans2b_007F } /* code 007F */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_00A0 } /* code 00A0 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_00A1 } /* code 00A1 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00A2 } /* code 00A2 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00A3 } /* code 00A3 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00A4 } /* code 00A4 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00A5 } /* code 00A5 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_00A6 } /* code 00A6 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00A7 } /* code 00A7 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_00A8 } /* code 00A8 */
  ,{   9,   9,  2, (void GUI_FLASH *)&acFontSans2b_00A9 } /* code 00A9 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_00AA } /* code 00AA */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00AB } /* code 00AB */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00AC } /* code 00AC */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_00AD } /* code 00AD */
  ,{   9,   9,  2, (void GUI_FLASH *)&acFontSans2b_00AE } /* code 00AE */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00AF } /* code 00AF */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans2b_00B0 } /* code 00B0 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00B1 } /* code 00B1 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_00B2 } /* code 00B2 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_00B3 } /* code 00B3 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_00B4 } /* code 00B4 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00B5 } /* code 00B5 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00B6 } /* code 00B6 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_00B7 } /* code 00B7 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_00B8 } /* code 00B8 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_00B9 } /* code 00B9 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans2b_00BA } /* code 00BA */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00BB } /* code 00BB */
  ,{  10,  10,  2, (void GUI_FLASH *)&acFontSans2b_00BC } /* code 00BC */
  ,{  10,  10,  2, (void GUI_FLASH *)&acFontSans2b_00BD } /* code 00BD */
  ,{  10,  10,  2, (void GUI_FLASH *)&acFontSans2b_00BE } /* code 00BE */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00BF } /* code 00BF */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_00C0 } /* code 00C0 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_00C1 } /* code 00C1 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_00C2 } /* code 00C2 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_00C3 } /* code 00C3 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_00C4 } /* code 00C4 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_00C5 } /* code 00C5 */
  ,{  13,  13,  2, (void GUI_FLASH *)&acFontSans2b_00C6 } /* code 00C6 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_00C7 } /* code 00C7 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00C8 } /* code 00C8 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00C9 } /* code 00C9 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00CA } /* code 00CA */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00CB } /* code 00CB */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_00CC } /* code 00CC */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_00CD } /* code 00CD */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_00CE } /* code 00CE */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_00CF } /* code 00CF */
  ,{   9,   9,  2, (void GUI_FLASH *)&acFontSans2b_00D0 } /* code 00D0 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_00D1 } /* code 00D1 */
  ,{   9,   9,  2, (void GUI_FLASH *)&acFontSans2b_00D2 } /* code 00D2 */
  ,{   9,   9,  2, (void GUI_FLASH *)&acFontSans2b_00D3 } /* code 00D3 */
  ,{   9,   9,  2, (void GUI_FLASH *)&acFontSans2b_00D4 } /* code 00D4 */
  ,{   9,   9,  2, (void GUI_FLASH *)&acFontSans2b_00D5 } /* code 00D5 */
  ,{   9,   9,  2, (void GUI_FLASH *)&acFontSans2b_00D6 } /* code 00D6 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00D7 } /* code 00D7 */
  ,{   9,   9,  2, (void GUI_FLASH *)&acFontSans2b_00D8 } /* code 00D8 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_00D9 } /* code 00D9 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_00DA } /* code 00DA */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_00DB } /* code 00DB */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_00DC } /* code 00DC */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00DD } /* code 00DD */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans2b_00DE } /* code 00DE */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00DF } /* code 00DF */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00E0 } /* code 00E0 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00E1 } /* code 00E1 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00E2 } /* code 00E2 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00E3 } /* code 00E3 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00E4 } /* code 00E4 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00E5 } /* code 00E5 */
  ,{  11,  11,  2, (void GUI_FLASH *)&acFontSans2b_00E6 } /* code 00E6 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00E7 } /* code 00E7 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00E8 } /* code 00E8 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00E9 } /* code 00E9 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00EA } /* code 00EA */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00EB } /* code 00EB */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_00EC } /* code 00EC */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_00ED } /* code 00ED */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_00EE } /* code 00EE */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans2b_00EF } /* code 00EF */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00F0 } /* code 00F0 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00F1 } /* code 00F1 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00F2 } /* code 00F2 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00F3 } /* code 00F3 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00F4 } /* code 00F4 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00F5 } /* code 00F5 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00F6 } /* code 00F6 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00F7 } /* code 00F7 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00F8 } /* code 00F8 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00F9 } /* code 00F9 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00FA } /* code 00FA */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00FB } /* code 00FB */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00FC } /* code 00FC */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans2b_00FD } /* code 00FD */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans2b_00FE } /* code 00FE */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans2b_00FF } /* code 00FF */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSans2b_Prop2 = {
   0x00A0 /* first character */
  ,0x00FF /* last character  */
  ,&GUI_FontSans2b_CharInfo[ 96] /* address of first character */
  ,(void*)0 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSans2b_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_FontSans2b_CharInfo[  0] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSans2b_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT GUI_FontSans2b = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,15 /* height of font  */
  ,15 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,(void GUI_FLASH *)&GUI_FontSans2b_Prop1
};

