/*
  C-file generated by Font converter for emWin V2.16a
  Compiled:    May 29 2002 at 16:54:45

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: Sans1b.c
  Font:        Arial
  Height:      10
*/

#include "GUI.H"

#ifndef GUI_FLASH
  #define GUI_FLASH
#endif

/* The following line needs to be included in any file selecting the
   font. A good place would be GUIConf.H
*/
extern GUI_FLASH const GUI_FONT GUI_FontSans1b;

GUI_FLASH const unsigned char acFontSans1b_0020[ 10] = { /* code 0020 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0021[ 10] = { /* code 0021 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0022[ 10] = { /* code 0022 */
  ________,
  ________,
  XXX_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0023[ 10] = { /* code 0023 */
  ________,
  ________,
  _X_X____,
  _X_X____,
  XXXX____,
  _X______,
  XXXX____,
  X_X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0024[ 10] = { /* code 0024 */
  ________,
  ________,
  _XX_____,
  X__X____,
  _X______,
  __XX____,
  X__X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0025[ 10] = { /* code 0025 */
  ________,
  ________,
  _XX_____,
  X_X_X___,
  X_XX____,
  ___X_X__,
  __X_X_X_,
  __X_X_X_,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0026[ 10] = { /* code 0026 */
  ________,
  ________,
  __XX____,
  _X_X____,
  __XX____,
  _XXXX___,
  X__XX___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0027[ 10] = { /* code 0027 */
  ________,
  ________,
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0028[ 10] = { /* code 0028 */
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  X_______,
  X_______,
  _X______,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0029[ 10] = { /* code 0029 */
  ________,
  ________,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______};

GUI_FLASH const unsigned char acFontSans1b_002A[ 10] = { /* code 002A */
  ________,
  ________,
  _X______,
  XXX_____,
  X_X_____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_002B[ 10] = { /* code 002B */
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  XXXX____,
  __X_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_002C[ 10] = { /* code 002C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontSans1b_002D[ 10] = { /* code 002D */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_002E[ 10] = { /* code 002E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_002F[ 10] = { /* code 002F */
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  ________,
  X_______,
  X_______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0030[ 10] = { /* code 0030 */
  ________,
  ________,
  _XX_____,
  _X_X____,
  X__X____,
  X__X____,
  XX_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0031[ 10] = { /* code 0031 */
  ________,
  ________,
  __X_____,
  _XX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0032[ 10] = { /* code 0032 */
  ________,
  ________,
  _XX_____,
  XX_X____,
  ___X____,
  __X_____,
  _X______,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0033[ 10] = { /* code 0033 */
  ________,
  ________,
  _XX_____,
  XX_X____,
  __XX____,
  ___X____,
  X__X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0034[ 10] = { /* code 0034 */
  ________,
  ________,
  __XX____,
  __XX____,
  _XXX____,
  X_XX____,
  XXXX____,
  __XX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0035[ 10] = { /* code 0035 */
  ________,
  ________,
  _XXX____,
  _X______,
  _XX_____,
  ___X____,
  ___X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0036[ 10] = { /* code 0036 */
  ________,
  ________,
  _XX_____,
  _X_X____,
  XXX_____,
  XX_X____,
  XX_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0037[ 10] = { /* code 0037 */
  ________,
  ________,
  XXXX____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0038[ 10] = { /* code 0038 */
  ________,
  ________,
  _XX_____,
  XX_X____,
  _XXX____,
  _X_X____,
  X__X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0039[ 10] = { /* code 0039 */
  ________,
  ________,
  _XX_____,
  X__X____,
  X__X____,
  _XXX____,
  ___X____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_003A[ 10] = { /* code 003A */
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_003B[ 10] = { /* code 003B */
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  _X______,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontSans1b_003C[ 10] = { /* code 003C */
  ________,
  ________,
  ________,
  ___X____,
  _XX_____,
  XX______,
  __XX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_003D[ 10] = { /* code 003D */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  ________,
  XXXX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_003E[ 10] = { /* code 003E */
  ________,
  ________,
  ________,
  XX______,
  _XXX____,
  __XX____,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_003F[ 10] = { /* code 003F */
  ________,
  ________,
  _XXX____,
  XX_X____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0040[ 10] = { /* code 0040 */
  ________,
  ________,
  __XXXX__,
  _X____X_,
  __XXXX__,
  X_X__X_X,
  X_X_X_X_,
  X_XXXX__,
  _X____X_,
  ___XXX__};

GUI_FLASH const unsigned char acFontSans1b_0041[ 10] = { /* code 0041 */
  ________,
  ________,
  __XX____,
  __XX____,
  _XXX____,
  _X__X___,
  _XXXX___,
  X___XX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0042[ 10] = { /* code 0042 */
  ________,
  ________,
  _XXX____,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0043[ 10] = { /* code 0043 */
  ________,
  ________,
  __XX____,
  _X__X___,
  XX______,
  XX______,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0044[ 10] = { /* code 0044 */
  ________,
  ________,
  _XXX____,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0045[ 10] = { /* code 0045 */
  ________,
  ________,
  _XXXX___,
  _X______,
  _X______,
  _X______,
  _X______,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0046[ 10] = { /* code 0046 */
  ________,
  ________,
  _XXXX___,
  _X______,
  _X______,
  _XXX____,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0047[ 10] = { /* code 0047 */
  ________,
  ________,
  __XXX___,
  _X__XX__,
  XX______,
  XX_XXX__,
  _X___X__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0048[ 10] = { /* code 0048 */
  ________,
  ________,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0049[ 10] = { /* code 0049 */
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_004A[ 10] = { /* code 004A */
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  X__X____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_004B[ 10] = { /* code 004B */
  ________,
  ________,
  _X__X___,
  _X_X____,
  _XX_____,
  _XXX____,
  _X_XX___,
  _X__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_004C[ 10] = { /* code 004C */
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_004D[ 10] = { /* code 004D */
  ________,
  ________,
  _X__XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XXX_X__,
  _X_X_X__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_004E[ 10] = { /* code 004E */
  ________,
  ________,
  _X__X___,
  _X__X___,
  _XX_X___,
  _XXXX___,
  _X_XX___,
  _X__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_004F[ 10] = { /* code 004F */
  ________,
  ________,
  __XXX___,
  _X__XX__,
  XX___X__,
  XX___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0050[ 10] = { /* code 0050 */
  ________,
  ________,
  _XXX____,
  _X__X___,
  _X__X___,
  _XXX____,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0051[ 10] = { /* code 0051 */
  ________,
  ________,
  __XXX___,
  _X__XX__,
  XX___X__,
  XX___X__,
  _X_XXX__,
  _XXXXX__,
  _____X__,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0052[ 10] = { /* code 0052 */
  ________,
  ________,
  _XXXX___,
  _X__X___,
  _X__X___,
  _XXX____,
  _X_XX___,
  _X__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0053[ 10] = { /* code 0053 */
  ________,
  ________,
  _XXX____,
  _X_XX___,
  _XX_____,
  __XXX___,
  XX__X___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0054[ 10] = { /* code 0054 */
  ________,
  ________,
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0055[ 10] = { /* code 0055 */
  ________,
  ________,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0056[ 10] = { /* code 0056 */
  ________,
  ________,
  X___X___,
  XX__X___,
  _X_XX___,
  _X_X____,
  __XX____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0057[ 20] = { /* code 0057 */
  ________,________,
  ________,________,
  X__XX_X_,________,
  X__XX_X_,________,
  _X_XX_X_,________,
  _XX_X_X_,________,
  _XX__XX_,________,
  _XX__X__,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontSans1b_0058[ 10] = { /* code 0058 */
  ________,
  ________,
  XX__X___,
  _X_X____,
  __XX____,
  __XX____,
  _X_X____,
  XX__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0059[ 10] = { /* code 0059 */
  ________,
  ________,
  X___X___,
  _X_XX___,
  _XXX____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_005A[ 10] = { /* code 005A */
  ________,
  ________,
  XXXXX___,
  ___X____,
  __XX____,
  _XX_____,
  XX______,
  XXXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_005B[ 10] = { /* code 005B */
  ________,
  ________,
  _XX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _XX_____};

GUI_FLASH const unsigned char acFontSans1b_005C[ 10] = { /* code 005C */
  ________,
  ________,
  X_______,
  X_______,
  ________,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_005D[ 10] = { /* code 005D */
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______};

GUI_FLASH const unsigned char acFontSans1b_005E[ 10] = { /* code 005E */
  ________,
  ________,
  __X_____,
  _XX_____,
  _X_X____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_005F[ 10] = { /* code 005F */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____};

GUI_FLASH const unsigned char acFontSans1b_0060[ 10] = { /* code 0060 */
  ________,
  ________,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0061[ 10] = { /* code 0061 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  __XX____,
  X__X____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0062[ 10] = { /* code 0062 */
  ________,
  ________,
  _X______,
  _X______,
  _XXX____,
  _X_XX___,
  _X_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0063[ 10] = { /* code 0063 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X_______,
  XX_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0064[ 10] = { /* code 0064 */
  ________,
  ________,
  ___X____,
  ___X____,
  _XXX____,
  X__X____,
  XX_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0065[ 10] = { /* code 0065 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X__X____,
  X_______,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0066[ 10] = { /* code 0066 */
  ________,
  ________,
  _XX_____,
  _X______,
  XXX_____,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0067[ 10] = { /* code 0067 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X__X____,
  XX_X____,
  _XXX____,
  XX_X____,
  _XXX____};

GUI_FLASH const unsigned char acFontSans1b_0068[ 10] = { /* code 0068 */
  ________,
  ________,
  _X______,
  _X______,
  _XXX____,
  _X_X____,
  _X_X____,
  _X_X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0069[ 10] = { /* code 0069 */
  ________,
  ________,
  _X______,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_006A[ 10] = { /* code 006A */
  ________,
  ________,
  _X______,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______,
  X_______};

GUI_FLASH const unsigned char acFontSans1b_006B[ 10] = { /* code 006B */
  ________,
  ________,
  _X______,
  _X______,
  _XXX____,
  _XX_____,
  _XXX____,
  _X_X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_006C[ 10] = { /* code 006C */
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_006D[ 10] = { /* code 006D */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  XX_X_XX_,
  XX_X_XX_,
  XX_X_XX_,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_006E[ 10] = { /* code 006E */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _X_X____,
  _X_X____,
  _X_X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_006F[ 10] = { /* code 006F */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X__XX___,
  XX_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0070[ 10] = { /* code 0070 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _X_XX___,
  _X_XX___,
  _XXX____,
  _X______,
  _X______};

GUI_FLASH const unsigned char acFontSans1b_0071[ 10] = { /* code 0071 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  XX_X____,
  XX_X____,
  _XXX____,
  ___X____,
  ___X____};

GUI_FLASH const unsigned char acFontSans1b_0072[ 10] = { /* code 0072 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0073[ 10] = { /* code 0073 */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  XXX_____,
  ___X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0074[ 10] = { /* code 0074 */
  ________,
  ________,
  ________,
  _X______,
  XX______,
  _X______,
  _X______,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0075[ 10] = { /* code 0075 */
  ________,
  ________,
  ________,
  ________,
  _X_X____,
  _X_X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0076[ 10] = { /* code 0076 */
  ________,
  ________,
  ________,
  ________,
  X__X____,
  _X_X____,
  _XX_____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0077[ 10] = { /* code 0077 */
  ________,
  ________,
  ________,
  ________,
  X_XX____,
  _XXX____,
  _XXXX___,
  _XX_X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0078[ 10] = { /* code 0078 */
  ________,
  ________,
  ________,
  ________,
  _X_X____,
  _XX_____,
  _XX_____,
  XX_X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_0079[ 10] = { /* code 0079 */
  ________,
  ________,
  ________,
  ________,
  X__X____,
  _X_X____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______};

GUI_FLASH const unsigned char acFontSans1b_007A[ 10] = { /* code 007A */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  __X_____,
  _X______,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_007B[ 10] = { /* code 007B */
  ________,
  ________,
  _XX_____,
  _X______,
  _X______,
  XX______,
  _X______,
  _X______,
  _X______,
  __X_____};

GUI_FLASH const unsigned char acFontSans1b_007C[ 10] = { /* code 007C */
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_FLASH const unsigned char acFontSans1b_007D[ 10] = { /* code 007D */
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _XX_____,
  _X______,
  _X______,
  _X______,
  X_______};

GUI_FLASH const unsigned char acFontSans1b_007E[ 10] = { /* code 007E */
  ________,
  ________,
  ________,
  ________,
  _X______,
  X_XX____,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_007F[ 10] = { /* code 007F */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00A0[ 10] = { /* code 00A0 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00A1[ 10] = { /* code 00A1 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_FLASH const unsigned char acFontSans1b_00A2[ 10] = { /* code 00A2 */
  ________,
  ________,
  ___X____,
  ________,
  _XXX____,
  X_X_____,
  XX_X____,
  _XXX____,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00A3[ 10] = { /* code 00A3 */
  ________,
  ________,
  _XX_____,
  _X_X____,
  _X______,
  XXX_____,
  _X______,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00A4[ 10] = { /* code 00A4 */
  ________,
  ________,
  ________,
  X_XX____,
  _X_X____,
  _X_X____,
  XXXX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00A5[ 10] = { /* code 00A5 */
  ________,
  ________,
  X__X____,
  _X_X____,
  _XX_____,
  XXXX____,
  XXXX____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00A6[ 10] = { /* code 00A6 */
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  ________,
  ________,
  _X______,
  _X______,
  _X______};

GUI_FLASH const unsigned char acFontSans1b_00A7[ 10] = { /* code 00A7 */
  ________,
  ________,
  _XX_____,
  _X_X____,
  _XX_____,
  X__X____,
  _X_X____,
  __XX____,
  XX_X____,
  _XX_____};

GUI_FLASH const unsigned char acFontSans1b_00A8[ 10] = { /* code 00A8 */
  ________,
  ________,
  X_X_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00A9[ 10] = { /* code 00A9 */
  ________,
  ________,
  __XX____,
  X_______,
  X____X__,
  X____X__,
  X_XX_X__,
  _X_XX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00AA[ 10] = { /* code 00AA */
  ________,
  ________,
  XXX_____,
  _XX_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00AB[ 10] = { /* code 00AB */
  ________,
  ________,
  ________,
  ________,
  _X_X____,
  _XX_____,
  _XX_____,
  _X_X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00AC[ 10] = { /* code 00AC */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00AD[ 10] = { /* code 00AD */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00AE[ 10] = { /* code 00AE */
  ________,
  ________,
  __XX____,
  X_______,
  X__X_X__,
  X__X_X__,
  X__X_X__,
  _X__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00AF[ 10] = { /* code 00AF */
  ________,
  XXXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00B0[ 10] = { /* code 00B0 */
  ________,
  ________,
  _X______,
  X_X_____,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00B1[ 10] = { /* code 00B1 */
  ________,
  ________,
  ________,
  __X_____,
  XXXX____,
  __X_____,
  __X_____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00B2[ 10] = { /* code 00B2 */
  ________,
  ________,
  XX______,
  _X______,
  X_______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00B3[ 10] = { /* code 00B3 */
  ________,
  ________,
  XX______,
  _X______,
  X_______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00B4[ 10] = { /* code 00B4 */
  ________,
  ________,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00B5[ 10] = { /* code 00B5 */
  ________,
  ________,
  ________,
  ________,
  XX_X____,
  XX_X____,
  XX_X____,
  XXXX____,
  XX______,
  XX______};

GUI_FLASH const unsigned char acFontSans1b_00B6[ 10] = { /* code 00B6 */
  ________,
  ________,
  _XXX____,
  XX_X____,
  XX_X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____};

GUI_FLASH const unsigned char acFontSans1b_00B7[ 10] = { /* code 00B7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00B8[ 10] = { /* code 00B8 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  XX______};

GUI_FLASH const unsigned char acFontSans1b_00B9[ 10] = { /* code 00B9 */
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00BA[ 10] = { /* code 00BA */
  ________,
  ________,
  _X______,
  X_X_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00BB[ 10] = { /* code 00BB */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _X_X____,
  _X_X____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00BC[ 10] = { /* code 00BC */
  ________,
  ________,
  _X______,
  _X__X___,
  _X_X____,
  _____X__,
  __X__X__,
  ____XXX_,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00BD[ 10] = { /* code 00BD */
  ________,
  ________,
  _X______,
  _X__X___,
  _X_X____,
  ____XX__,
  __X__X__,
  ____X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00BE[ 10] = { /* code 00BE */
  ________,
  ________,
  XX______,
  _X__X___,
  X_______,
  ___X_X__,
  __X__X__,
  ____XXX_,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00BF[ 10] = { /* code 00BF */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  _XX_____,
  _X______,
  XX_X____,
  __X_____};

GUI_FLASH const unsigned char acFontSans1b_00C0[ 10] = { /* code 00C0 */
  ________,
  __XX____,
  __XX____,
  __XX____,
  _XXX____,
  _X__X___,
  _XXXX___,
  X___XX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00C1[ 10] = { /* code 00C1 */
  ________,
  __X_____,
  __XX____,
  __XX____,
  _XXX____,
  _X__X___,
  _XXXX___,
  X___XX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00C2[ 10] = { /* code 00C2 */
  ________,
  ___X____,
  __XX____,
  __XX____,
  _XXX____,
  _X__X___,
  _XXXX___,
  X___XX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00C3[ 10] = { /* code 00C3 */
  ________,
  _X_X____,
  __XX____,
  __XX____,
  _XXX____,
  _X__X___,
  _XXXX___,
  X___XX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00C4[ 10] = { /* code 00C4 */
  ________,
  _X_X____,
  __XX____,
  __XX____,
  _XXX____,
  _X__X___,
  _XXXX___,
  X___XX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00C5[ 10] = { /* code 00C5 */
  ________,
  ________,
  __XX____,
  __XX____,
  _XXX____,
  _X__X___,
  _XXXX___,
  X___XX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00C6[ 10] = { /* code 00C6 */
  ________,
  ________,
  __XXXXXX,
  __X_X___,
  _X__X___,
  _X__X___,
  XXXXX___,
  X___XXXX,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00C7[ 10] = { /* code 00C7 */
  ________,
  ________,
  __XX____,
  _X__X___,
  XX______,
  XX______,
  _X__X___,
  _XXXX___,
  ___X____,
  __XX____};

GUI_FLASH const unsigned char acFontSans1b_00C8[ 10] = { /* code 00C8 */
  ________,
  _XX_____,
  _XXXX___,
  _X______,
  _X______,
  _X______,
  _X______,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00C9[ 10] = { /* code 00C9 */
  ________,
  __X_____,
  _XXXX___,
  _X______,
  _X______,
  _X______,
  _X______,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00CA[ 10] = { /* code 00CA */
  ________,
  __X_____,
  _XXXX___,
  _X______,
  _X______,
  _X______,
  _X______,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00CB[ 10] = { /* code 00CB */
  ________,
  _X_X____,
  _XXXX___,
  _X______,
  _X______,
  _X______,
  _X______,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00CC[ 10] = { /* code 00CC */
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00CD[ 10] = { /* code 00CD */
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00CE[ 10] = { /* code 00CE */
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00CF[ 10] = { /* code 00CF */
  ________,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00D0[ 10] = { /* code 00D0 */
  ________,
  ________,
  _XXX____,
  _X__X___,
  _X__X___,
  XXX_X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00D1[ 10] = { /* code 00D1 */
  ________,
  __X_X___,
  _X__X___,
  _X__X___,
  _XX_X___,
  _XXXX___,
  _X_XX___,
  _X__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00D2[ 10] = { /* code 00D2 */
  ________,
  __XX____,
  __XXX___,
  _X__XX__,
  XX___X__,
  XX___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00D3[ 10] = { /* code 00D3 */
  ________,
  ___X____,
  __XXX___,
  _X__XX__,
  XX___X__,
  XX___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00D4[ 10] = { /* code 00D4 */
  ________,
  ___X____,
  __XXX___,
  _X__XX__,
  XX___X__,
  XX___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00D5[ 10] = { /* code 00D5 */
  ________,
  __X_X___,
  __XXX___,
  _X__XX__,
  XX___X__,
  XX___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00D6[ 10] = { /* code 00D6 */
  ________,
  __X_X___,
  __XXX___,
  _X__XX__,
  XX___X__,
  XX___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00D7[ 10] = { /* code 00D7 */
  ________,
  ________,
  ________,
  ___X____,
  _XXX____,
  _XX_____,
  _X_X____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00D8[ 10] = { /* code 00D8 */
  ________,
  ________,
  __XXXX__,
  _X__XX__,
  XX_X_X__,
  XXX__X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00D9[ 10] = { /* code 00D9 */
  ________,
  __XX____,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00DA[ 10] = { /* code 00DA */
  ________,
  __X_____,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00DB[ 10] = { /* code 00DB */
  ________,
  ___X____,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00DC[ 10] = { /* code 00DC */
  ________,
  __X_X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00DD[ 10] = { /* code 00DD */
  ________,
  __X_____,
  X___X___,
  _X_XX___,
  _XXX____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00DE[ 10] = { /* code 00DE */
  ________,
  ________,
  _X______,
  _XXX____,
  _X__X___,
  _X__X___,
  _XXX____,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00DF[ 10] = { /* code 00DF */
  ________,
  ________,
  _XX_____,
  _X_X____,
  _XX_____,
  _XXX____,
  _X_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00E0[ 10] = { /* code 00E0 */
  ________,
  ________,
  _XX_____,
  ________,
  _XXX____,
  __XX____,
  X__X____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00E1[ 10] = { /* code 00E1 */
  ________,
  ________,
  __X_____,
  ________,
  _XXX____,
  __XX____,
  X__X____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00E2[ 10] = { /* code 00E2 */
  ________,
  ________,
  __X_____,
  ________,
  _XXX____,
  __XX____,
  X__X____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00E3[ 10] = { /* code 00E3 */
  ________,
  ________,
  _X_X____,
  ________,
  _XXX____,
  __XX____,
  X__X____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00E4[ 10] = { /* code 00E4 */
  ________,
  ________,
  _X_X____,
  ________,
  _XXX____,
  __XX____,
  X__X____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00E5[ 10] = { /* code 00E5 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  __XX____,
  X__X____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00E6[ 10] = { /* code 00E6 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  __XX__X_,
  XX_X____,
  _XXXXX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00E7[ 10] = { /* code 00E7 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X_______,
  XX_X____,
  _XXX____,
  __X_____,
  _XX_____};

GUI_FLASH const unsigned char acFontSans1b_00E8[ 10] = { /* code 00E8 */
  ________,
  ________,
  _XX_____,
  ________,
  _XXX____,
  X__X____,
  X_______,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00E9[ 10] = { /* code 00E9 */
  ________,
  ________,
  __X_____,
  ________,
  _XXX____,
  X__X____,
  X_______,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00EA[ 10] = { /* code 00EA */
  ________,
  ________,
  __X_____,
  ________,
  _XXX____,
  X__X____,
  X_______,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00EB[ 10] = { /* code 00EB */
  ________,
  ________,
  _X_X____,
  ________,
  _XXX____,
  X__X____,
  X_______,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00EC[ 10] = { /* code 00EC */
  ________,
  ________,
  XX______,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00ED[ 10] = { /* code 00ED */
  ________,
  ________,
  _X______,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00EE[ 10] = { /* code 00EE */
  ________,
  ________,
  _X______,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00EF[ 10] = { /* code 00EF */
  ________,
  ________,
  X_______,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00F0[ 10] = { /* code 00F0 */
  ________,
  ________,
  __XX____,
  _X_X____,
  _XXX____,
  XX_XX___,
  XX_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00F1[ 10] = { /* code 00F1 */
  ________,
  ________,
  _X_X____,
  ________,
  _XXX____,
  _X_X____,
  _X_X____,
  _X_X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00F2[ 10] = { /* code 00F2 */
  ________,
  ________,
  _XX_____,
  ________,
  _XXX____,
  X__XX___,
  XX_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00F3[ 10] = { /* code 00F3 */
  ________,
  ________,
  __X_____,
  ________,
  _XXX____,
  X__XX___,
  XX_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00F4[ 10] = { /* code 00F4 */
  ________,
  ________,
  __X_____,
  ________,
  _XXX____,
  X__XX___,
  XX_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00F5[ 10] = { /* code 00F5 */
  ________,
  ________,
  _X_X____,
  ________,
  _XXX____,
  X__XX___,
  XX_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00F6[ 10] = { /* code 00F6 */
  ________,
  ________,
  _X_X____,
  ________,
  _XXX____,
  X__XX___,
  XX_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00F7[ 10] = { /* code 00F7 */
  ________,
  ________,
  ________,
  __X_____,
  ________,
  XXXX____,
  __X_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00F8[ 10] = { /* code 00F8 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X_XXX___,
  XX_XX___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00F9[ 10] = { /* code 00F9 */
  ________,
  ________,
  _XX_____,
  ________,
  _X_X____,
  _X_X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00FA[ 10] = { /* code 00FA */
  ________,
  ________,
  __X_____,
  ________,
  _X_X____,
  _X_X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00FB[ 10] = { /* code 00FB */
  ________,
  ________,
  __X_____,
  ________,
  _X_X____,
  _X_X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00FC[ 10] = { /* code 00FC */
  ________,
  ________,
  _X_X____,
  ________,
  _X_X____,
  _X_X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontSans1b_00FD[ 10] = { /* code 00FD */
  ________,
  ________,
  __X_____,
  ________,
  X__X____,
  _X_X____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______};

GUI_FLASH const unsigned char acFontSans1b_00FE[ 10] = { /* code 00FE */
  ________,
  ________,
  _X______,
  _X______,
  _XXX____,
  _X_XX___,
  _X_XX___,
  _XXX____,
  _X______,
  _X______};

GUI_FLASH const unsigned char acFontSans1b_00FF[ 10] = { /* code 00FF */
  ________,
  ________,
  _X_X____,
  ________,
  X__X____,
  _X_X____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______};

GUI_FLASH const GUI_CHARINFO GUI_FontSans1b_CharInfo[192] = {
   {   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_0020 } /* code 0020 */
  ,{   1,   1,  1, (void GUI_FLASH *)&acFontSans1b_0021 } /* code 0021 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0022 } /* code 0022 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0023 } /* code 0023 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0024 } /* code 0024 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans1b_0025 } /* code 0025 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_0026 } /* code 0026 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_0027 } /* code 0027 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_0028 } /* code 0028 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_0029 } /* code 0029 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_002A } /* code 002A */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_002B } /* code 002B */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_002C } /* code 002C */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_002D } /* code 002D */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_002E } /* code 002E */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_002F } /* code 002F */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0030 } /* code 0030 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0031 } /* code 0031 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0032 } /* code 0032 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0033 } /* code 0033 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0034 } /* code 0034 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0035 } /* code 0035 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0036 } /* code 0036 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0037 } /* code 0037 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0038 } /* code 0038 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0039 } /* code 0039 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_003A } /* code 003A */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_003B } /* code 003B */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_003C } /* code 003C */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_003D } /* code 003D */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_003E } /* code 003E */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_003F } /* code 003F */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans1b_0040 } /* code 0040 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_0041 } /* code 0041 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_0042 } /* code 0042 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_0043 } /* code 0043 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_0044 } /* code 0044 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0045 } /* code 0045 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0046 } /* code 0046 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_0047 } /* code 0047 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_0048 } /* code 0048 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_0049 } /* code 0049 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_004A } /* code 004A */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_004B } /* code 004B */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_004C } /* code 004C */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans1b_004D } /* code 004D */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_004E } /* code 004E */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_004F } /* code 004F */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0050 } /* code 0050 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_0051 } /* code 0051 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_0052 } /* code 0052 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0053 } /* code 0053 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0054 } /* code 0054 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_0055 } /* code 0055 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0056 } /* code 0056 */
  ,{   9,   9,  2, (void GUI_FLASH *)&acFontSans1b_0057 } /* code 0057 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0058 } /* code 0058 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0059 } /* code 0059 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_005A } /* code 005A */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_005B } /* code 005B */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_005C } /* code 005C */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_005D } /* code 005D */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_005E } /* code 005E */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_005F } /* code 005F */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_0060 } /* code 0060 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0061 } /* code 0061 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0062 } /* code 0062 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0063 } /* code 0063 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0064 } /* code 0064 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0065 } /* code 0065 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_0066 } /* code 0066 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0067 } /* code 0067 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0068 } /* code 0068 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_0069 } /* code 0069 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_006A } /* code 006A */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_006B } /* code 006B */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_006C } /* code 006C */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans1b_006D } /* code 006D */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_006E } /* code 006E */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_006F } /* code 006F */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0070 } /* code 0070 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0071 } /* code 0071 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_0072 } /* code 0072 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0073 } /* code 0073 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_0074 } /* code 0074 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0075 } /* code 0075 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0076 } /* code 0076 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_0077 } /* code 0077 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0078 } /* code 0078 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_0079 } /* code 0079 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_007A } /* code 007A */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_007B } /* code 007B */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_007C } /* code 007C */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_007D } /* code 007D */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_007E } /* code 007E */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_007F } /* code 007F */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_00A0 } /* code 00A0 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_00A1 } /* code 00A1 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00A2 } /* code 00A2 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00A3 } /* code 00A3 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00A4 } /* code 00A4 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00A5 } /* code 00A5 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_00A6 } /* code 00A6 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00A7 } /* code 00A7 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_00A8 } /* code 00A8 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00A9 } /* code 00A9 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_00AA } /* code 00AA */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00AB } /* code 00AB */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00AC } /* code 00AC */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_00AD } /* code 00AD */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00AE } /* code 00AE */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00AF } /* code 00AF */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_00B0 } /* code 00B0 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00B1 } /* code 00B1 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_00B2 } /* code 00B2 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_00B3 } /* code 00B3 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_00B4 } /* code 00B4 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00B5 } /* code 00B5 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00B6 } /* code 00B6 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_00B7 } /* code 00B7 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_00B8 } /* code 00B8 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_00B9 } /* code 00B9 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontSans1b_00BA } /* code 00BA */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00BB } /* code 00BB */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans1b_00BC } /* code 00BC */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans1b_00BD } /* code 00BD */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans1b_00BE } /* code 00BE */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00BF } /* code 00BF */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00C0 } /* code 00C0 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00C1 } /* code 00C1 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00C2 } /* code 00C2 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00C3 } /* code 00C3 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00C4 } /* code 00C4 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00C5 } /* code 00C5 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontSans1b_00C6 } /* code 00C6 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00C7 } /* code 00C7 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00C8 } /* code 00C8 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00C9 } /* code 00C9 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00CA } /* code 00CA */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00CB } /* code 00CB */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_00CC } /* code 00CC */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_00CD } /* code 00CD */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_00CE } /* code 00CE */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_00CF } /* code 00CF */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00D0 } /* code 00D0 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00D1 } /* code 00D1 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00D2 } /* code 00D2 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00D3 } /* code 00D3 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00D4 } /* code 00D4 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00D5 } /* code 00D5 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00D6 } /* code 00D6 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00D7 } /* code 00D7 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00D8 } /* code 00D8 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00D9 } /* code 00D9 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00DA } /* code 00DA */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00DB } /* code 00DB */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontSans1b_00DC } /* code 00DC */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00DD } /* code 00DD */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00DE } /* code 00DE */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00DF } /* code 00DF */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00E0 } /* code 00E0 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00E1 } /* code 00E1 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00E2 } /* code 00E2 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00E3 } /* code 00E3 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00E4 } /* code 00E4 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00E5 } /* code 00E5 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontSans1b_00E6 } /* code 00E6 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00E7 } /* code 00E7 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00E8 } /* code 00E8 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00E9 } /* code 00E9 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00EA } /* code 00EA */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00EB } /* code 00EB */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_00EC } /* code 00EC */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_00ED } /* code 00ED */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_00EE } /* code 00EE */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontSans1b_00EF } /* code 00EF */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00F0 } /* code 00F0 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00F1 } /* code 00F1 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00F2 } /* code 00F2 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00F3 } /* code 00F3 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00F4 } /* code 00F4 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00F5 } /* code 00F5 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00F6 } /* code 00F6 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00F7 } /* code 00F7 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00F8 } /* code 00F8 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00F9 } /* code 00F9 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00FA } /* code 00FA */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00FB } /* code 00FB */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00FC } /* code 00FC */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00FD } /* code 00FD */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontSans1b_00FE } /* code 00FE */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontSans1b_00FF } /* code 00FF */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSans1b_Prop2 = {
   0x00A0 /* first character */
  ,0x00FF /* last character  */
  ,&GUI_FontSans1b_CharInfo[ 96] /* address of first character */
  ,(void*)0 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSans1b_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_FontSans1b_CharInfo[  0] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSans1b_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT GUI_FontSans1b = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,10 /* height of font  */
  ,10 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,(void GUI_FLASH *)&GUI_FontSans1b_Prop1
};

