/*
  C-file generated by Font converter for emWin V2.16a
  Compiled:    May 29 2002 at 16:54:45

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: Times1.c
  Font:        Times New Roman
  Height:      10
*/

#include "GUI.H"

#ifndef GUI_FLASH
  #define GUI_FLASH
#endif

/* The following line needs to be included in any file selecting the
   font. A good place would be GUIConf.H
*/
extern GUI_FLASH const GUI_FONT GUI_FontTimes1;

GUI_FLASH const unsigned char acFontTimes1_0020[ 10] = { /* code 0020 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0021[ 10] = { /* code 0021 */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0022[ 10] = { /* code 0022 */
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0023[ 10] = { /* code 0023 */
  ________,
  ________,
  ________,
  _XX_____,
  XXXX____,
  X_X_____,
  XXX_____,
  X_X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0024[ 10] = { /* code 0024 */
  ________,
  ________,
  ________,
  XXX_____,
  _X______,
  __X_____,
  _X_X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0025[ 10] = { /* code 0025 */
  ________,
  ________,
  ________,
  XX__X___,
  XX_X____,
  __X__X__,
  __X_XX__,
  _X__XX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0026[ 10] = { /* code 0026 */
  ________,
  ________,
  ________,
  _XXX____,
  __X_____,
  _XX_X___,
  X__X____,
  XXX_XX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0027[ 10] = { /* code 0027 */
  ________,
  ________,
  ________,
  X_______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0028[ 10] = { /* code 0028 */
  ________,
  ________,
  ________,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0029[ 10] = { /* code 0029 */
  ________,
  ________,
  ________,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______};

GUI_FLASH const unsigned char acFontTimes1_002A[ 10] = { /* code 002A */
  ________,
  ________,
  ________,
  _X______,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_002B[ 10] = { /* code 002B */
  ________,
  ________,
  ________,
  ________,
  _X______,
  XXXX____,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_002C[ 10] = { /* code 002C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______,
  ________};

GUI_FLASH const unsigned char acFontTimes1_002D[ 10] = { /* code 002D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_002E[ 10] = { /* code 002E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_002F[ 10] = { /* code 002F */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  X_______,
  X_______,
  X_______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0030[ 10] = { /* code 0030 */
  ________,
  ________,
  ________,
  XXX_____,
  X__X____,
  X__X____,
  X__X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0031[ 10] = { /* code 0031 */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0032[ 10] = { /* code 0032 */
  ________,
  ________,
  ________,
  XXX_____,
  __X_____,
  __X_____,
  _X______,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0033[ 10] = { /* code 0033 */
  ________,
  ________,
  ________,
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0034[ 10] = { /* code 0034 */
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  X_X_____,
  XXXX____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0035[ 10] = { /* code 0035 */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  __X_____,
  __X_____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0036[ 10] = { /* code 0036 */
  ________,
  ________,
  ________,
  _XX_____,
  X_______,
  XXXX____,
  X__X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0037[ 10] = { /* code 0037 */
  ________,
  ________,
  ________,
  XXX_____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0038[ 10] = { /* code 0038 */
  ________,
  ________,
  ________,
  XXX_____,
  _XX_____,
  _XX_____,
  X__X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0039[ 10] = { /* code 0039 */
  ________,
  ________,
  ________,
  XXX_____,
  X__X____,
  X__X____,
  _XX_____,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_003A[ 10] = { /* code 003A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_003B[ 10] = { /* code 003B */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontTimes1_003C[ 10] = { /* code 003C */
  ________,
  ________,
  ________,
  ________,
  __XX____,
  XX______,
  __X_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_003D[ 10] = { /* code 003D */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_003E[ 10] = { /* code 003E */
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  ___X____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_003F[ 10] = { /* code 003F */
  ________,
  ________,
  ________,
  XXX_____,
  __X_____,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0040[ 10] = { /* code 0040 */
  ________,
  ________,
  ___XX___,
  _XX__X__,
  X__XX_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_XXXXX_,
  X_____X_,
  _XXXXX__};

GUI_FLASH const unsigned char acFontTimes1_0041[ 10] = { /* code 0041 */
  ________,
  ________,
  ________,
  __X_____,
  _X_X____,
  _X_X____,
  X_X_X___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0042[ 10] = { /* code 0042 */
  ________,
  ________,
  ________,
  _XXX____,
  _X__X___,
  _XXX____,
  _X__X___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0043[ 10] = { /* code 0043 */
  ________,
  ________,
  ________,
  _XXXX___,
  X_______,
  X_______,
  X_______,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0044[ 10] = { /* code 0044 */
  ________,
  ________,
  ________,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0045[ 10] = { /* code 0045 */
  ________,
  ________,
  ________,
  _XXX____,
  _X_X____,
  _XXX____,
  _X______,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0046[ 10] = { /* code 0046 */
  ________,
  ________,
  ________,
  _XXX____,
  _X______,
  _XX_____,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0047[ 10] = { /* code 0047 */
  ________,
  ________,
  ________,
  _XXXX___,
  X_______,
  X___X___,
  X___X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0048[ 10] = { /* code 0048 */
  ________,
  ________,
  ________,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0049[ 10] = { /* code 0049 */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_004A[ 10] = { /* code 004A */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_004B[ 10] = { /* code 004B */
  ________,
  ________,
  ________,
  _X_X____,
  _XX_____,
  _XX_____,
  _X_X____,
  _X__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_004C[ 10] = { /* code 004C */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_004D[ 10] = { /* code 004D */
  ________,
  ________,
  ________,
  _X___X__,
  XX___X__,
  X_X_XX__,
  X_XX_X__,
  X__X_X__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_004E[ 10] = { /* code 004E */
  ________,
  ________,
  ________,
  _X__X___,
  X_X_X___,
  X__XX___,
  X__XX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_004F[ 10] = { /* code 004F */
  ________,
  ________,
  ________,
  _XXXX___,
  X___X___,
  X___X___,
  X___X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0050[ 10] = { /* code 0050 */
  ________,
  ________,
  ________,
  _XXX____,
  _X_X____,
  _XX_____,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0051[ 10] = { /* code 0051 */
  ________,
  ________,
  ________,
  _XXXX___,
  X___X___,
  X___X___,
  X___X___,
  _X__X___,
  __XX____,
  ____X___};

GUI_FLASH const unsigned char acFontTimes1_0052[ 10] = { /* code 0052 */
  ________,
  ________,
  ________,
  _XXX____,
  _X_X____,
  _XX_____,
  _X_X____,
  _X__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0053[ 10] = { /* code 0053 */
  ________,
  ________,
  ________,
  XXXX____,
  _X______,
  __X_____,
  ___X____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0054[ 10] = { /* code 0054 */
  ________,
  ________,
  ________,
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0055[ 10] = { /* code 0055 */
  ________,
  ________,
  ________,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0056[ 10] = { /* code 0056 */
  ________,
  ________,
  ________,
  _X__X___,
  _X__X___,
  __XX____,
  __XX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0057[ 10] = { /* code 0057 */
  ________,
  ________,
  ________,
  _X_X__X_,
  _X__XX__,
  _X_XXX__,
  __X_XX__,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0058[ 10] = { /* code 0058 */
  ________,
  ________,
  ________,
  _X_XX___,
  __XX____,
  ___X____,
  _XXX____,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0059[ 10] = { /* code 0059 */
  ________,
  ________,
  ________,
  _X__X___,
  _X_X____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_005A[ 10] = { /* code 005A */
  ________,
  ________,
  ________,
  _XXX____,
  __X_____,
  __X_____,
  _X______,
  XXXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_005B[ 10] = { /* code 005B */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_FLASH const unsigned char acFontTimes1_005C[ 10] = { /* code 005C */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  _X______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_005D[ 10] = { /* code 005D */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______};

GUI_FLASH const unsigned char acFontTimes1_005E[ 10] = { /* code 005E */
  ________,
  ________,
  ________,
  _X______,
  X_X_____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_005F[ 10] = { /* code 005F */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____};

GUI_FLASH const unsigned char acFontTimes1_0060[ 10] = { /* code 0060 */
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0061[ 10] = { /* code 0061 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X_X_____,
  XXX_____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0062[ 10] = { /* code 0062 */
  ________,
  ________,
  ________,
  X_______,
  X_X_____,
  XX_X____,
  X__X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0063[ 10] = { /* code 0063 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X_______,
  X_______,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0064[ 10] = { /* code 0064 */
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  X_X_____,
  X_X_____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0065[ 10] = { /* code 0065 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X_X_____,
  XX______,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0066[ 10] = { /* code 0066 */
  ________,
  ________,
  __X_____,
  _X______,
  XXX_____,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0067[ 10] = { /* code 0067 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X_X_____,
  _XX_____,
  _XX_____,
  X__X____,
  _XX_____};

GUI_FLASH const unsigned char acFontTimes1_0068[ 10] = { /* code 0068 */
  ________,
  ________,
  ________,
  X_______,
  X_X_____,
  XXX_____,
  X_X_____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0069[ 10] = { /* code 0069 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_006A[ 10] = { /* code 006A */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______,
  X_______};

GUI_FLASH const unsigned char acFontTimes1_006B[ 10] = { /* code 006B */
  ________,
  ________,
  ________,
  X_______,
  X_XX____,
  XX______,
  XX______,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_006C[ 10] = { /* code 006C */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_006D[ 10] = { /* code 006D */
  ________,
  ________,
  ________,
  ________,
  __X_X___,
  XXXX_X__,
  X_X__X__,
  XXXXXX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_006E[ 10] = { /* code 006E */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  XXX_____,
  X_X_____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_006F[ 10] = { /* code 006F */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X__X____,
  X__X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0070[ 10] = { /* code 0070 */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  XX_X____,
  X__X____,
  X_X_____,
  XX______,
  X_______};

GUI_FLASH const unsigned char acFontTimes1_0071[ 10] = { /* code 0071 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X_X_____,
  X_X_____,
  _XX_____,
  __X_____,
  ___X____};

GUI_FLASH const unsigned char acFontTimes1_0072[ 10] = { /* code 0072 */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  XX______,
  X_______,
  X_______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0073[ 10] = { /* code 0073 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X_X_____,
  _XX_____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0074[ 10] = { /* code 0074 */
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_______,
  X_______,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0075[ 10] = { /* code 0075 */
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  X_X_____,
  X_X_____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0076[ 10] = { /* code 0076 */
  ________,
  ________,
  ________,
  ________,
  XX_X____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0077[ 10] = { /* code 0077 */
  ________,
  ________,
  ________,
  ________,
  XXXX_X__,
  X_X_X___,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0078[ 10] = { /* code 0078 */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  _X______,
  _XX_____,
  X_X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_0079[ 10] = { /* code 0079 */
  ________,
  ________,
  ________,
  ________,
  XX_X____,
  _XX_____,
  _XX_____,
  _X______,
  _X______,
  X_______};

GUI_FLASH const unsigned char acFontTimes1_007A[ 10] = { /* code 007A */
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  __X_____,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_007B[ 10] = { /* code 007B */
  ________,
  ________,
  ________,
  _XX_____,
  __X_____,
  _X______,
  _X______,
  __X_____,
  _X______,
  __X_____};

GUI_FLASH const unsigned char acFontTimes1_007C[ 10] = { /* code 007C */
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_FLASH const unsigned char acFontTimes1_007D[ 10] = { /* code 007D */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontTimes1_007E[ 10] = { /* code 007E */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_007F[ 10] = { /* code 007F */
  ________,
  ________,
  ________,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00A0[ 10] = { /* code 00A0 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00A1[ 10] = { /* code 00A1 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  _X______,
  _X______,
  _X______};

GUI_FLASH const unsigned char acFontTimes1_00A2[ 10] = { /* code 00A2 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  XX______,
  XX______,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00A3[ 10] = { /* code 00A3 */
  ________,
  ________,
  ________,
  _XXX____,
  _X______,
  _X______,
  _X______,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00A4[ 10] = { /* code 00A4 */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  X__X____,
  XXX_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00A5[ 10] = { /* code 00A5 */
  ________,
  ________,
  ________,
  X_X_____,
  _XX_____,
  XXXX____,
  XXXX____,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00A6[ 10] = { /* code 00A6 */
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  ________,
  ________,
  _X______,
  _X______,
  _X______};

GUI_FLASH const unsigned char acFontTimes1_00A7[ 10] = { /* code 00A7 */
  ________,
  ________,
  ________,
  _XX_____,
  _X______,
  _XX_____,
  _XX_____,
  __X_____,
  __X_____,
  _X______};

GUI_FLASH const unsigned char acFontTimes1_00A8[ 10] = { /* code 00A8 */
  ________,
  ________,
  ________,
  X_______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00A9[ 10] = { /* code 00A9 */
  ________,
  ________,
  ________,
  XXXXX___,
  XX___X__,
  XX___X__,
  XX_XXX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00AA[ 10] = { /* code 00AA */
  ________,
  ________,
  ________,
  _X______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00AB[ 10] = { /* code 00AB */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  XXX_____,
  X_X_____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00AC[ 10] = { /* code 00AC */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00AD[ 10] = { /* code 00AD */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00AE[ 10] = { /* code 00AE */
  ________,
  ________,
  ________,
  XXXXX___,
  XX_X_X__,
  XXX__X__,
  XX_X_X__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00AF[ 10] = { /* code 00AF */
  ________,
  XXXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00B0[ 10] = { /* code 00B0 */
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00B1[ 10] = { /* code 00B1 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  XXXX____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00B2[ 10] = { /* code 00B2 */
  ________,
  ________,
  ________,
  _X______,
  X_______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00B3[ 10] = { /* code 00B3 */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00B4[ 10] = { /* code 00B4 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00B5[ 10] = { /* code 00B5 */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  _X_X____,
  _X_X____,
  _XXX____,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00B6[ 10] = { /* code 00B6 */
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00B7[ 10] = { /* code 00B7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00B8[ 10] = { /* code 00B8 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00B9[ 10] = { /* code 00B9 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00BA[ 10] = { /* code 00BA */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00BB[ 10] = { /* code 00BB */
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_X_____,
  _XX_____,
  X_X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00BC[ 10] = { /* code 00BC */
  ________,
  ________,
  ________,
  ___X____,
  _X_X____,
  __X_____,
  __XXX___,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00BD[ 10] = { /* code 00BD */
  ________,
  ________,
  ________,
  ___X____,
  _X_X____,
  __X_X___,
  _X___X__,
  _X__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00BE[ 10] = { /* code 00BE */
  ________,
  ________,
  ________,
  _X_X____,
  _X_X____,
  __X_____,
  _X_XX___,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00BF[ 10] = { /* code 00BF */
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  _X______,
  X_______,
  X_X_____,
  _XX_____};

GUI_FLASH const unsigned char acFontTimes1_00C0[ 10] = { /* code 00C0 */
  ________,
  ___X____,
  ________,
  __X_____,
  _X_X____,
  _X_X____,
  X_X_X___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00C1[ 10] = { /* code 00C1 */
  ________,
  ________,
  ________,
  __X_____,
  _X_X____,
  _X_X____,
  X_X_X___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00C2[ 10] = { /* code 00C2 */
  ________,
  __XX____,
  ________,
  __X_____,
  _X_X____,
  _X_X____,
  X_X_X___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00C3[ 10] = { /* code 00C3 */
  ________,
  ________,
  _XXX____,
  __X_____,
  _X_X____,
  _X_X____,
  X_X_X___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00C4[ 10] = { /* code 00C4 */
  ________,
  ________,
  __X_____,
  __X_____,
  _X_X____,
  _X_X____,
  X_X_X___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00C5[ 10] = { /* code 00C5 */
  ________,
  ___X____,
  __XX____,
  __X_____,
  _X_X____,
  _X_X____,
  X_X_X___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00C6[ 10] = { /* code 00C6 */
  ________,
  ________,
  ________,
  ___XXX__,
  _XXX_X__,
  _X_XX___,
  X_XX____,
  XXXXXXX_,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00C7[ 10] = { /* code 00C7 */
  ________,
  ________,
  ________,
  _XXXX___,
  X_______,
  X_______,
  X_______,
  _X__X___,
  __XX____,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00C8[ 10] = { /* code 00C8 */
  ________,
  __X_____,
  ________,
  _XXX____,
  _X_X____,
  _XXX____,
  _X______,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00C9[ 10] = { /* code 00C9 */
  ________,
  ________,
  ________,
  _XXX____,
  _X_X____,
  _XXX____,
  _X______,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00CA[ 10] = { /* code 00CA */
  ________,
  _XX_____,
  ________,
  _XXX____,
  _X_X____,
  _XXX____,
  _X______,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00CB[ 10] = { /* code 00CB */
  ________,
  ________,
  _X______,
  _XXX____,
  _X_X____,
  _XXX____,
  _X______,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00CC[ 10] = { /* code 00CC */
  ________,
  _X______,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00CD[ 10] = { /* code 00CD */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00CE[ 10] = { /* code 00CE */
  ________,
  XX______,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00CF[ 10] = { /* code 00CF */
  ________,
  ________,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00D0[ 10] = { /* code 00D0 */
  ________,
  ________,
  ________,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00D1[ 10] = { /* code 00D1 */
  ________,
  ________,
  _XXX____,
  _X__X___,
  X_X_X___,
  X__XX___,
  X__XX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00D2[ 10] = { /* code 00D2 */
  ________,
  ___X____,
  ________,
  _XXXX___,
  X___X___,
  X___X___,
  X___X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00D3[ 10] = { /* code 00D3 */
  ________,
  ________,
  ________,
  _XXXX___,
  X___X___,
  X___X___,
  X___X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00D4[ 10] = { /* code 00D4 */
  ________,
  __XX____,
  ________,
  _XXXX___,
  X___X___,
  X___X___,
  X___X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00D5[ 10] = { /* code 00D5 */
  ________,
  ________,
  _XXX____,
  _X__X___,
  X___X___,
  X___X___,
  X___X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00D6[ 10] = { /* code 00D6 */
  ________,
  ________,
  __X_____,
  _X_XX___,
  X___X___,
  X___X___,
  X___X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00D7[ 10] = { /* code 00D7 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  __X_____,
  _X_X____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00D8[ 10] = { /* code 00D8 */
  ________,
  ________,
  ________,
  _XXXX___,
  X__XX___,
  X_X_X___,
  XX__X___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00D9[ 10] = { /* code 00D9 */
  ________,
  ___X____,
  ________,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00DA[ 10] = { /* code 00DA */
  ________,
  ________,
  ________,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00DB[ 10] = { /* code 00DB */
  ________,
  __XX____,
  ________,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00DC[ 10] = { /* code 00DC */
  ________,
  ________,
  __X_____,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00DD[ 10] = { /* code 00DD */
  ________,
  ________,
  ________,
  _X__X___,
  _X_X____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00DE[ 10] = { /* code 00DE */
  ________,
  ________,
  ________,
  _X______,
  _XXX____,
  _X_X____,
  _XXX____,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00DF[ 10] = { /* code 00DF */
  ________,
  ________,
  __X_____,
  XXX_____,
  X_X_____,
  X__X____,
  X__X____,
  X_X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00E0[ 10] = { /* code 00E0 */
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  X_X_____,
  XXX_____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00E1[ 10] = { /* code 00E1 */
  ________,
  ________,
  ________,
  X_______,
  _XX_____,
  X_X_____,
  XXX_____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00E2[ 10] = { /* code 00E2 */
  ________,
  ________,
  ________,
  XX______,
  _XX_____,
  X_X_____,
  XXX_____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00E3[ 10] = { /* code 00E3 */
  ________,
  ________,
  ________,
  XX______,
  _XX_____,
  X_X_____,
  XXX_____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00E4[ 10] = { /* code 00E4 */
  ________,
  ________,
  ________,
  X_______,
  _XX_____,
  X_X_____,
  XXX_____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00E5[ 10] = { /* code 00E5 */
  ________,
  ________,
  _X______,
  XX______,
  _XX_____,
  X_X_____,
  XXX_____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00E6[ 10] = { /* code 00E6 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  X_X_X___,
  XXXX____,
  XX_XX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00E7[ 10] = { /* code 00E7 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X_______,
  X_______,
  _XX_____,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00E8[ 10] = { /* code 00E8 */
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  X_X_____,
  XX______,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00E9[ 10] = { /* code 00E9 */
  ________,
  ________,
  ________,
  _X______,
  _XX_____,
  X_X_____,
  XX______,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00EA[ 10] = { /* code 00EA */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  X_X_____,
  XX______,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00EB[ 10] = { /* code 00EB */
  ________,
  ________,
  ________,
  _X______,
  _XX_____,
  X_X_____,
  XX______,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00EC[ 10] = { /* code 00EC */
  ________,
  ________,
  ________,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00ED[ 10] = { /* code 00ED */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00EE[ 10] = { /* code 00EE */
  ________,
  ________,
  ________,
  XX______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00EF[ 10] = { /* code 00EF */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00F0[ 10] = { /* code 00F0 */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  X__X____,
  X__X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00F1[ 10] = { /* code 00F1 */
  ________,
  ________,
  ________,
  XXX_____,
  X_X_____,
  XXX_____,
  X_X_____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00F2[ 10] = { /* code 00F2 */
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  X__X____,
  X__X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00F3[ 10] = { /* code 00F3 */
  ________,
  ________,
  ________,
  _X______,
  _XX_____,
  X__X____,
  X__X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00F4[ 10] = { /* code 00F4 */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  X__X____,
  X__X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00F5[ 10] = { /* code 00F5 */
  ________,
  ________,
  ________,
  XXX_____,
  _XX_____,
  X__X____,
  X__X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00F6[ 10] = { /* code 00F6 */
  ________,
  ________,
  ________,
  _X______,
  _XX_____,
  X__X____,
  X__X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00F7[ 10] = { /* code 00F7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  __X_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00F8[ 10] = { /* code 00F8 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X_XX____,
  XX_X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00F9[ 10] = { /* code 00F9 */
  ________,
  ________,
  ________,
  __X_____,
  X_X_____,
  X_X_____,
  X_X_____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00FA[ 10] = { /* code 00FA */
  ________,
  ________,
  ________,
  _X______,
  X_X_____,
  X_X_____,
  X_X_____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00FB[ 10] = { /* code 00FB */
  ________,
  ________,
  ________,
  _XX_____,
  X_X_____,
  X_X_____,
  X_X_____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00FC[ 10] = { /* code 00FC */
  ________,
  ________,
  ________,
  _X______,
  X_X_____,
  X_X_____,
  X_X_____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1_00FD[ 10] = { /* code 00FD */
  ________,
  ________,
  ________,
  _X______,
  XX_X____,
  _XX_____,
  _XX_____,
  _X______,
  _X______,
  X_______};

GUI_FLASH const unsigned char acFontTimes1_00FE[ 10] = { /* code 00FE */
  ________,
  ________,
  ________,
  X_______,
  X_X_____,
  XX_X____,
  X__X____,
  X_X_____,
  XX______,
  X_______};

GUI_FLASH const unsigned char acFontTimes1_00FF[ 10] = { /* code 00FF */
  ________,
  ________,
  ________,
  _X______,
  XX_X____,
  _XX_____,
  _XX_____,
  _X______,
  _X______,
  X_______};

GUI_FLASH const GUI_CHARINFO GUI_FontTimes1_CharInfo[192] = {
   {   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_0020 } /* code 0020 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_0021 } /* code 0021 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_0022 } /* code 0022 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0023 } /* code 0023 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0024 } /* code 0024 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontTimes1_0025 } /* code 0025 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_0026 } /* code 0026 */
  ,{   1,   1,  1, (void GUI_FLASH *)&acFontTimes1_0027 } /* code 0027 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_0028 } /* code 0028 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_0029 } /* code 0029 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_002A } /* code 002A */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_002B } /* code 002B */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_002C } /* code 002C */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_002D } /* code 002D */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_002E } /* code 002E */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_002F } /* code 002F */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0030 } /* code 0030 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0031 } /* code 0031 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0032 } /* code 0032 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0033 } /* code 0033 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0034 } /* code 0034 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0035 } /* code 0035 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0036 } /* code 0036 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0037 } /* code 0037 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0038 } /* code 0038 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0039 } /* code 0039 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_003A } /* code 003A */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_003B } /* code 003B */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_003C } /* code 003C */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_003D } /* code 003D */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_003E } /* code 003E */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_003F } /* code 003F */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontTimes1_0040 } /* code 0040 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_0041 } /* code 0041 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_0042 } /* code 0042 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_0043 } /* code 0043 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_0044 } /* code 0044 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_0045 } /* code 0045 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0046 } /* code 0046 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_0047 } /* code 0047 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_0048 } /* code 0048 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_0049 } /* code 0049 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_004A } /* code 004A */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_004B } /* code 004B */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_004C } /* code 004C */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontTimes1_004D } /* code 004D */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_004E } /* code 004E */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_004F } /* code 004F */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0050 } /* code 0050 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_0051 } /* code 0051 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_0052 } /* code 0052 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0053 } /* code 0053 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_0054 } /* code 0054 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_0055 } /* code 0055 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_0056 } /* code 0056 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontTimes1_0057 } /* code 0057 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_0058 } /* code 0058 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_0059 } /* code 0059 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_005A } /* code 005A */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_005B } /* code 005B */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_005C } /* code 005C */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_005D } /* code 005D */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_005E } /* code 005E */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_005F } /* code 005F */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_0060 } /* code 0060 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0061 } /* code 0061 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0062 } /* code 0062 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0063 } /* code 0063 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0064 } /* code 0064 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0065 } /* code 0065 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_0066 } /* code 0066 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0067 } /* code 0067 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0068 } /* code 0068 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_0069 } /* code 0069 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_006A } /* code 006A */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_006B } /* code 006B */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_006C } /* code 006C */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_006D } /* code 006D */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_006E } /* code 006E */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_006F } /* code 006F */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0070 } /* code 0070 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0071 } /* code 0071 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_0072 } /* code 0072 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_0073 } /* code 0073 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_0074 } /* code 0074 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0075 } /* code 0075 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0076 } /* code 0076 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_0077 } /* code 0077 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0078 } /* code 0078 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_0079 } /* code 0079 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_007A } /* code 007A */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_007B } /* code 007B */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_007C } /* code 007C */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_007D } /* code 007D */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_007E } /* code 007E */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_007F } /* code 007F */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_00A0 } /* code 00A0 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_00A1 } /* code 00A1 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00A2 } /* code 00A2 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00A3 } /* code 00A3 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00A4 } /* code 00A4 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00A5 } /* code 00A5 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_00A6 } /* code 00A6 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00A7 } /* code 00A7 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_00A8 } /* code 00A8 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00A9 } /* code 00A9 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_00AA } /* code 00AA */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00AB } /* code 00AB */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_00AC } /* code 00AC */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_00AD } /* code 00AD */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00AE } /* code 00AE */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00AF } /* code 00AF */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_00B0 } /* code 00B0 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00B1 } /* code 00B1 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_00B2 } /* code 00B2 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_00B3 } /* code 00B3 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_00B4 } /* code 00B4 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_00B5 } /* code 00B5 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00B6 } /* code 00B6 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_00B7 } /* code 00B7 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_00B8 } /* code 00B8 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_00B9 } /* code 00B9 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_00BA } /* code 00BA */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00BB } /* code 00BB */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00BC } /* code 00BC */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00BD } /* code 00BD */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00BE } /* code 00BE */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_00BF } /* code 00BF */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00C0 } /* code 00C0 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00C1 } /* code 00C1 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00C2 } /* code 00C2 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00C3 } /* code 00C3 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00C4 } /* code 00C4 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00C5 } /* code 00C5 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontTimes1_00C6 } /* code 00C6 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_00C7 } /* code 00C7 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_00C8 } /* code 00C8 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_00C9 } /* code 00C9 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_00CA } /* code 00CA */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_00CB } /* code 00CB */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_00CC } /* code 00CC */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_00CD } /* code 00CD */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_00CE } /* code 00CE */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1_00CF } /* code 00CF */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontTimes1_00D0 } /* code 00D0 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00D1 } /* code 00D1 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00D2 } /* code 00D2 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00D3 } /* code 00D3 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00D4 } /* code 00D4 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00D5 } /* code 00D5 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00D6 } /* code 00D6 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_00D7 } /* code 00D7 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00D8 } /* code 00D8 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00D9 } /* code 00D9 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00DA } /* code 00DA */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00DB } /* code 00DB */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00DC } /* code 00DC */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1_00DD } /* code 00DD */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_00DE } /* code 00DE */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00DF } /* code 00DF */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00E0 } /* code 00E0 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00E1 } /* code 00E1 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00E2 } /* code 00E2 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00E3 } /* code 00E3 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00E4 } /* code 00E4 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00E5 } /* code 00E5 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_00E6 } /* code 00E6 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00E7 } /* code 00E7 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00E8 } /* code 00E8 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00E9 } /* code 00E9 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00EA } /* code 00EA */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00EB } /* code 00EB */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_00EC } /* code 00EC */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_00ED } /* code 00ED */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_00EE } /* code 00EE */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1_00EF } /* code 00EF */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00F0 } /* code 00F0 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00F1 } /* code 00F1 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00F2 } /* code 00F2 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00F3 } /* code 00F3 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00F4 } /* code 00F4 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00F5 } /* code 00F5 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00F6 } /* code 00F6 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00F7 } /* code 00F7 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00F8 } /* code 00F8 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00F9 } /* code 00F9 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00FA } /* code 00FA */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00FB } /* code 00FB */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1_00FC } /* code 00FC */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_00FD } /* code 00FD */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_00FE } /* code 00FE */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1_00FF } /* code 00FF */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontTimes1_Prop2 = {
   0x00A0 /* first character */
  ,0x00FF /* last character  */
  ,&GUI_FontTimes1_CharInfo[ 96] /* address of first character */
  ,(void*)0 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontTimes1_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_FontTimes1_CharInfo[  0] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontTimes1_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT GUI_FontTimes1 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,10 /* height of font  */
  ,10 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,(void GUI_FLASH *)&GUI_FontTimes1_Prop1
};

