/*
  C-file generated by Font converter for emWin V2.16a
  Compiled:    May 29 2002 at 16:54:45

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: Times1b.c
  Font:        Times New Roman
  Height:      11
*/

#include "GUI.H"

#ifndef GUI_FLASH
  #define GUI_FLASH
#endif

/* The following line needs to be included in any file selecting the
   font. A good place would be GUIConf.H
*/
extern GUI_FLASH const GUI_FONT GUI_FontTimes1b;

GUI_FLASH const unsigned char acFontTimes1b_0020[ 11] = { /* code 0020 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0021[ 11] = { /* code 0021 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  ________,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0022[ 11] = { /* code 0022 */
  ________,
  ________,
  ________,
  ________,
  _X_X____,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0023[ 11] = { /* code 0023 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  XXXX____,
  X_X_____,
  XXX_____,
  X_X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0024[ 11] = { /* code 0024 */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  XX______,
  _XX_____,
  _X_X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0025[ 22] = { /* code 0025 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX__X__,________,
  _XX_X___,________,
  ___X__X_,________,
  ___X_XX_,________,
  __X__XX_,________,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontTimes1b_0026[ 11] = { /* code 0026 */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  __XX____,
  _XXXX___,
  XX_XX___,
  _XXXXX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0027[ 11] = { /* code 0027 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0028[ 11] = { /* code 0028 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X______,
  __X_____};

GUI_FLASH const unsigned char acFontTimes1b_0029[ 11] = { /* code 0029 */
  ________,
  ________,
  ________,
  ________,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______};

GUI_FLASH const unsigned char acFontTimes1b_002A[ 11] = { /* code 002A */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_002B[ 11] = { /* code 002B */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  XXXX____,
  __X_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_002C[ 11] = { /* code 002C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_002D[ 11] = { /* code 002D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_002E[ 11] = { /* code 002E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_002F[ 11] = { /* code 002F */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  X_______,
  X_______,
  X_______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0030[ 11] = { /* code 0030 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X_XX____,
  X_XX____,
  X_XX____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0031[ 11] = { /* code 0031 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0032[ 11] = { /* code 0032 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  __X_____,
  __X_____,
  _X_X____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0033[ 11] = { /* code 0033 */
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  __X_____,
  __X_____,
  ___X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0034[ 11] = { /* code 0034 */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  X_X_____,
  XXXX____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0035[ 11] = { /* code 0035 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _X______,
  __XX____,
  ___X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0036[ 11] = { /* code 0036 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _X______,
  X_XX____,
  XX_X____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0037[ 11] = { /* code 0037 */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  __X_____,
  __X_____,
  __X_____,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0038[ 11] = { /* code 0038 */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  XXX_____,
  _XX_____,
  X__X____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0039[ 11] = { /* code 0039 */
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  X__X____,
  _XXX____,
  __X_____,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_003A[ 11] = { /* code 003A */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  ________,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_003B[ 11] = { /* code 003B */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  ________,
  _X______,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_003C[ 11] = { /* code 003C */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  XX______,
  __XX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_003D[ 11] = { /* code 003D */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_003E[ 11] = { /* code 003E */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  ___X____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_003F[ 11] = { /* code 003F */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  __X_____,
  ________,
  ________,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0040[ 11] = { /* code 0040 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  X__X_XX_,
  X_X_X_X_,
  X_X_X_X_,
  X_XXXXX_,
  _X____X_,
  __XXXX__};

GUI_FLASH const unsigned char acFontTimes1b_0041[ 11] = { /* code 0041 */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  __XX____,
  _X_X____,
  X_XXX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0042[ 11] = { /* code 0042 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _X_XX___,
  _XXX____,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0043[ 11] = { /* code 0043 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  XX______,
  XX______,
  _X______,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0044[ 11] = { /* code 0044 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0045[ 11] = { /* code 0045 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _X______,
  _XX_____,
  _X______,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0046[ 11] = { /* code 0046 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _X_X____,
  _XXX____,
  _X_X____,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0047[ 11] = { /* code 0047 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX______,
  XX______,
  _X__XX__,
  _XXXXX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0048[ 11] = { /* code 0048 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0049[ 11] = { /* code 0049 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_004A[ 11] = { /* code 004A */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  __X_____,
  X_X_____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_004B[ 11] = { /* code 004B */
  ________,
  ________,
  ________,
  ________,
  _X__X___,
  _X_X____,
  _XXX____,
  _X_XX___,
  _X__XX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_004C[ 11] = { /* code 004C */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_004D[ 11] = { /* code 004D */
  ________,
  ________,
  ________,
  ________,
  _XX__XX_,
  X_X__XX_,
  X_XXXXX_,
  X__X_XX_,
  X__X_XX_,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_004E[ 11] = { /* code 004E */
  ________,
  ________,
  ________,
  ________,
  _XX_X___,
  X_X_X___,
  X__XX___,
  X__XX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_004F[ 11] = { /* code 004F */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  XX__XX__,
  XX___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0050[ 11] = { /* code 0050 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _X_XX___,
  _XX_____,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0051[ 11] = { /* code 0051 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  XX__XX__,
  XX___X__,
  _X__XX__,
  _X__X___,
  __XXX___,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0052[ 11] = { /* code 0052 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _X__X___,
  _XXX____,
  _X_XX___,
  _X__X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0053[ 11] = { /* code 0053 */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  XX______,
  _XXX____,
  X__X____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0054[ 11] = { /* code 0054 */
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0055[ 11] = { /* code 0055 */
  ________,
  ________,
  ________,
  ________,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0056[ 11] = { /* code 0056 */
  ________,
  ________,
  ________,
  ________,
  _X__X___,
  _XXX____,
  __XX____,
  __XX____,
  __X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0057[ 11] = { /* code 0057 */
  ________,
  ________,
  ________,
  ________,
  _X__X_X_,
  _X__X_X_,
  _XXXXXX_,
  __X__X__,
  __X__X__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0058[ 11] = { /* code 0058 */
  ________,
  ________,
  ________,
  ________,
  _X__X___,
  __XX____,
  __XX____,
  _X_X____,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0059[ 11] = { /* code 0059 */
  ________,
  ________,
  ________,
  ________,
  _X__X___,
  _XXX____,
  __XX____,
  __XX____,
  __XX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_005A[ 11] = { /* code 005A */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  __XX____,
  __X_____,
  _XX_____,
  XXXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_005B[ 11] = { /* code 005B */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_005C[ 11] = { /* code 005C */
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  _X______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_005D[ 11] = { /* code 005D */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_005E[ 11] = { /* code 005E */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  _X_X____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_005F[ 11] = { /* code 005F */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____};

GUI_FLASH const unsigned char acFontTimes1b_0060[ 11] = { /* code 0060 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0061[ 11] = { /* code 0061 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  XXX_____,
  _XX_____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0062[ 11] = { /* code 0062 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _XX_____,
  _X_X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0063[ 11] = { /* code 0063 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X_X_____,
  X_______,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0064[ 11] = { /* code 0064 */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  _XXX____,
  X__X____,
  X__X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0065[ 11] = { /* code 0065 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X_X_____,
  XX______,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0066[ 11] = { /* code 0066 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  XX______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0067[ 11] = { /* code 0067 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X_X_____,
  _XX_____,
  X_______,
  _XXX____,
  _XX_____};

GUI_FLASH const unsigned char acFontTimes1b_0068[ 11] = { /* code 0068 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _XXX____,
  _X_X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0069[ 11] = { /* code 0069 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  XX______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_006A[ 11] = { /* code 006A */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______};

GUI_FLASH const unsigned char acFontTimes1b_006B[ 11] = { /* code 006B */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _XX_____,
  _XX_____,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_006C[ 11] = { /* code 006C */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_006D[ 11] = { /* code 006D */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  _X_X_X__,
  _X_X_X__,
  _XXX_X__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_006E[ 11] = { /* code 006E */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  _X_X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_006F[ 11] = { /* code 006F */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X__X____,
  X__X____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0070[ 11] = { /* code 0070 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  _X_X____,
  _X_X____,
  _X_X____,
  _XX_____,
  XX______};

GUI_FLASH const unsigned char acFontTimes1b_0071[ 11] = { /* code 0071 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  X__X____,
  X__X____,
  _XXX____,
  ___X____,
  ___X____};

GUI_FLASH const unsigned char acFontTimes1b_0072[ 11] = { /* code 0072 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0073[ 11] = { /* code 0073 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  XX______,
  _XX_____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0074[ 11] = { /* code 0074 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  XXX_____,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0075[ 11] = { /* code 0075 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  _X_X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0076[ 11] = { /* code 0076 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_X____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0077[ 11] = { /* code 0077 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX_X__,
  _X_XX___,
  _XXXX___,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0078[ 11] = { /* code 0078 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  _XX_____,
  __X_____,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_0079[ 11] = { /* code 0079 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_X____,
  _XX_____,
  _XX_____,
  _X______,
  _X______,
  XX______};

GUI_FLASH const unsigned char acFontTimes1b_007A[ 11] = { /* code 007A */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  __X_____,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_007B[ 11] = { /* code 007B */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  __X_____};

GUI_FLASH const unsigned char acFontTimes1b_007C[ 11] = { /* code 007C */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_FLASH const unsigned char acFontTimes1b_007D[ 11] = { /* code 007D */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______};

GUI_FLASH const unsigned char acFontTimes1b_007E[ 11] = { /* code 007E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_007F[ 11] = { /* code 007F */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00A0[ 11] = { /* code 00A0 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00A1[ 11] = { /* code 00A1 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  _X______,
  _X______,
  _X______};

GUI_FLASH const unsigned char acFontTimes1b_00A2[ 11] = { /* code 00A2 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _X______,
  _X______,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00A3[ 11] = { /* code 00A3 */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _X______,
  XXX_____,
  _X______,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00A4[ 11] = { /* code 00A4 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  X__X____,
  XXXX____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00A5[ 11] = { /* code 00A5 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00A6[ 11] = { /* code 00A6 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  ________,
  ________,
  _X______,
  _X______,
  _X______};

GUI_FLASH const unsigned char acFontTimes1b_00A7[ 11] = { /* code 00A7 */
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  _X______,
  X_X_____,
  XX_X____,
  _XX_____,
  _XX_____,
  _XX_____};

GUI_FLASH const unsigned char acFontTimes1b_00A8[ 11] = { /* code 00A8 */
  ________,
  ________,
  ________,
  ________,
  X_______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00A9[ 11] = { /* code 00A9 */
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  XX___X__,
  XX___X__,
  X_X__X__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00AA[ 11] = { /* code 00AA */
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00AB[ 11] = { /* code 00AB */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  _XX_____,
  X_X_____,
  _X_X____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00AC[ 11] = { /* code 00AC */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00AD[ 11] = { /* code 00AD */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00AE[ 11] = { /* code 00AE */
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  X_XX_X__,
  X_XX_X__,
  X_XX_X__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00AF[ 11] = { /* code 00AF */
  ________,
  ________,
  XXXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00B0[ 11] = { /* code 00B0 */
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00B1[ 11] = { /* code 00B1 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  XXXX____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00B2[ 11] = { /* code 00B2 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  X_______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00B3[ 11] = { /* code 00B3 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00B4[ 11] = { /* code 00B4 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00B5[ 11] = { /* code 00B5 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X_X____,
  _X_X____,
  _X_X____,
  _XXX____,
  X_______,
  X_______};

GUI_FLASH const unsigned char acFontTimes1b_00B6[ 11] = { /* code 00B6 */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  XXXX____,
  XXXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_FLASH const unsigned char acFontTimes1b_00B7[ 11] = { /* code 00B7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00B8[ 11] = { /* code 00B8 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00B9[ 11] = { /* code 00B9 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00BA[ 11] = { /* code 00BA */
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00BB[ 11] = { /* code 00BB */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_X_____,
  _X_X____,
  X_X_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00BC[ 11] = { /* code 00BC */
  ________,
  ________,
  ________,
  ________,
  _X__X___,
  _X_X____,
  __X__X__,
  __X_XX__,
  _X__XX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00BD[ 11] = { /* code 00BD */
  ________,
  ________,
  ________,
  ________,
  _X__X___,
  _X_X____,
  __X_X___,
  __X__X__,
  _X__XX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00BE[ 11] = { /* code 00BE */
  ________,
  ________,
  ________,
  ________,
  _X__X___,
  _X_X____,
  __X__X__,
  __X_XX__,
  _X__XX__,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00BF[ 11] = { /* code 00BF */
  ________,
  ________,
  ________,
  ________,
  ________,
  __X_____,
  ________,
  ________,
  _X______,
  XX_X____,
  _XX_____};

GUI_FLASH const unsigned char acFontTimes1b_00C0[ 11] = { /* code 00C0 */
  ________,
  ________,
  ___X____,
  ________,
  __X_____,
  __XX____,
  _X_X____,
  X_XXX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00C1[ 11] = { /* code 00C1 */
  ________,
  ________,
  ___X____,
  ________,
  __X_____,
  __XX____,
  _X_X____,
  X_XXX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00C2[ 11] = { /* code 00C2 */
  ________,
  ___X____,
  __XX____,
  ________,
  __X_____,
  __XX____,
  _X_X____,
  X_XXX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00C3[ 11] = { /* code 00C3 */
  ________,
  ________,
  __XX____,
  ________,
  __X_____,
  __XX____,
  _X_X____,
  X_XXX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00C4[ 11] = { /* code 00C4 */
  ________,
  ________,
  __X_____,
  ________,
  __X_____,
  __XX____,
  _X_X____,
  X_XXX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00C5[ 11] = { /* code 00C5 */
  ________,
  ________,
  ___X____,
  __XX____,
  __X_____,
  __XX____,
  _X_X____,
  X_XXX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00C6[ 11] = { /* code 00C6 */
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  __X_X___,
  __XXXX__,
  _X__X__X,
  X___XXX_,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00C7[ 11] = { /* code 00C7 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  XX______,
  XX______,
  _X______,
  _XX_X___,
  ___X____,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00C8[ 11] = { /* code 00C8 */
  ________,
  ________,
  __X_____,
  ________,
  _XXXX___,
  _X______,
  _XX_____,
  _X______,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00C9[ 11] = { /* code 00C9 */
  ________,
  ________,
  __X_____,
  ________,
  _XXXX___,
  _X______,
  _XX_____,
  _X______,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00CA[ 11] = { /* code 00CA */
  ________,
  __X_____,
  _XX_____,
  ________,
  _XXXX___,
  _X______,
  _XX_____,
  _X______,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00CB[ 11] = { /* code 00CB */
  ________,
  ________,
  _X______,
  ________,
  _XXXX___,
  _X______,
  _XX_____,
  _X______,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00CC[ 11] = { /* code 00CC */
  ________,
  ________,
  _X______,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00CD[ 11] = { /* code 00CD */
  ________,
  ________,
  _X______,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00CE[ 11] = { /* code 00CE */
  ________,
  _X______,
  XX______,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00CF[ 11] = { /* code 00CF */
  ________,
  ________,
  X_______,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00D0[ 11] = { /* code 00D0 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00D1[ 11] = { /* code 00D1 */
  ________,
  ________,
  __XX____,
  ________,
  _XX_X___,
  X_X_X___,
  X__XX___,
  X__XX___,
  X___X___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00D2[ 11] = { /* code 00D2 */
  ________,
  ________,
  ___X____,
  ________,
  _XXXX___,
  XX__XX__,
  XX___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00D3[ 11] = { /* code 00D3 */
  ________,
  ________,
  ___X____,
  ________,
  _XXXX___,
  XX__XX__,
  XX___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00D4[ 11] = { /* code 00D4 */
  ________,
  ___X____,
  __XX____,
  ________,
  _XXXX___,
  XX__XX__,
  XX___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00D5[ 11] = { /* code 00D5 */
  ________,
  ________,
  __XX____,
  ________,
  _XXXX___,
  XX__XX__,
  XX___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00D6[ 11] = { /* code 00D6 */
  ________,
  ________,
  __X_____,
  ________,
  _XXXX___,
  XX__XX__,
  XX___X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00D7[ 11] = { /* code 00D7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X_X____,
  __X_____,
  _X_X____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00D8[ 11] = { /* code 00D8 */
  ________,
  ________,
  ________,
  _____X__,
  _XXXX___,
  XX__XX__,
  XXXX_X__,
  _X__XX__,
  _XXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00D9[ 11] = { /* code 00D9 */
  ________,
  ________,
  ___X____,
  ________,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00DA[ 11] = { /* code 00DA */
  ________,
  ________,
  __X_____,
  ________,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00DB[ 11] = { /* code 00DB */
  ________,
  ___X____,
  __XX____,
  ________,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00DC[ 11] = { /* code 00DC */
  ________,
  ________,
  __X_____,
  ________,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00DD[ 11] = { /* code 00DD */
  ________,
  ________,
  ___X____,
  ________,
  _X__X___,
  _XXX____,
  __XX____,
  __XX____,
  __XX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00DE[ 11] = { /* code 00DE */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _XXX____,
  _X_XX___,
  _XXX____,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00DF[ 11] = { /* code 00DF */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _X_X____,
  _XXX____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00E0[ 11] = { /* code 00E0 */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  XXX_____,
  _XX_____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00E1[ 11] = { /* code 00E1 */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  XXX_____,
  _XX_____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00E2[ 11] = { /* code 00E2 */
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  _XX_____,
  XXX_____,
  _XX_____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00E3[ 11] = { /* code 00E3 */
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  _XX_____,
  XXX_____,
  _XX_____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00E4[ 11] = { /* code 00E4 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  XXX_____,
  _XX_____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00E5[ 11] = { /* code 00E5 */
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  _XX_____,
  XXX_____,
  _XX_____,
  XXXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00E6[ 11] = { /* code 00E6 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  X_X_X___,
  _XXX____,
  XXXXX___,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00E7[ 11] = { /* code 00E7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X_X_____,
  X_______,
  _XX_____,
  __X_____,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00E8[ 11] = { /* code 00E8 */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  X_X_____,
  XX______,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00E9[ 11] = { /* code 00E9 */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _XX_____,
  X_X_____,
  XX______,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00EA[ 11] = { /* code 00EA */
  ________,
  ________,
  ________,
  _X______,
  XX______,
  _XX_____,
  X_X_____,
  XX______,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00EB[ 11] = { /* code 00EB */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  X_X_____,
  XX______,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00EC[ 11] = { /* code 00EC */
  ________,
  ________,
  ________,
  ________,
  _X______,
  XX______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00ED[ 11] = { /* code 00ED */
  ________,
  ________,
  ________,
  ________,
  _X______,
  XX______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00EE[ 11] = { /* code 00EE */
  ________,
  ________,
  ________,
  _X______,
  XX______,
  XX______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00EF[ 11] = { /* code 00EF */
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00F0[ 11] = { /* code 00F0 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  X__X____,
  X__X____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00F1[ 11] = { /* code 00F1 */
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XXXX____,
  _X_X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00F2[ 11] = { /* code 00F2 */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  X__X____,
  X__X____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00F3[ 11] = { /* code 00F3 */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  X__X____,
  X__X____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00F4[ 11] = { /* code 00F4 */
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  _XX_____,
  X__X____,
  X__X____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00F5[ 11] = { /* code 00F5 */
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  _XX_____,
  X__X____,
  X__X____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00F6[ 11] = { /* code 00F6 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  X__X____,
  X__X____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00F7[ 11] = { /* code 00F7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  __X_____,
  ________,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00F8[ 11] = { /* code 00F8 */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  XXXX____,
  XX_X____,
  _XX_____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00F9[ 11] = { /* code 00F9 */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  XXXX____,
  _X_X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00FA[ 11] = { /* code 00FA */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  XXXX____,
  _X_X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00FB[ 11] = { /* code 00FB */
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  XXXX____,
  _X_X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00FC[ 11] = { /* code 00FC */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  XXXX____,
  _X_X____,
  _X_X____,
  _XXX____,
  ________,
  ________};

GUI_FLASH const unsigned char acFontTimes1b_00FD[ 11] = { /* code 00FD */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  XX_X____,
  _XX_____,
  _XX_____,
  _X______,
  _X______,
  XX______};

GUI_FLASH const unsigned char acFontTimes1b_00FE[ 11] = { /* code 00FE */
  ________,
  ________,
  ________,
  ________,
  _X______,
  _XX_____,
  _X_X____,
  _X_X____,
  _X_X____,
  _XX_____,
  XX______};

GUI_FLASH const unsigned char acFontTimes1b_00FF[ 11] = { /* code 00FF */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  XX_X____,
  _XX_____,
  _XX_____,
  _X______,
  _X______,
  XX______};

GUI_FLASH const GUI_CHARINFO GUI_FontTimes1b_CharInfo[192] = {
   {   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_0020 } /* code 0020 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_0021 } /* code 0021 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0022 } /* code 0022 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0023 } /* code 0023 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0024 } /* code 0024 */
  ,{   9,   9,  2, (void GUI_FLASH *)&acFontTimes1b_0025 } /* code 0025 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontTimes1b_0026 } /* code 0026 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_0027 } /* code 0027 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_0028 } /* code 0028 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_0029 } /* code 0029 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_002A } /* code 002A */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_002B } /* code 002B */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_002C } /* code 002C */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_002D } /* code 002D */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_002E } /* code 002E */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_002F } /* code 002F */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0030 } /* code 0030 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0031 } /* code 0031 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0032 } /* code 0032 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0033 } /* code 0033 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0034 } /* code 0034 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0035 } /* code 0035 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0036 } /* code 0036 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0037 } /* code 0037 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0038 } /* code 0038 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0039 } /* code 0039 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_003A } /* code 003A */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_003B } /* code 003B */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_003C } /* code 003C */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_003D } /* code 003D */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_003E } /* code 003E */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_003F } /* code 003F */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontTimes1b_0040 } /* code 0040 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_0041 } /* code 0041 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_0042 } /* code 0042 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_0043 } /* code 0043 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_0044 } /* code 0044 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_0045 } /* code 0045 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_0046 } /* code 0046 */
  ,{   7,   7,  1, (void GUI_FLASH *)&acFontTimes1b_0047 } /* code 0047 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_0048 } /* code 0048 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_0049 } /* code 0049 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_004A } /* code 004A */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_004B } /* code 004B */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_004C } /* code 004C */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontTimes1b_004D } /* code 004D */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_004E } /* code 004E */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_004F } /* code 004F */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_0050 } /* code 0050 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontTimes1b_0051 } /* code 0051 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_0052 } /* code 0052 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0053 } /* code 0053 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_0054 } /* code 0054 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_0055 } /* code 0055 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_0056 } /* code 0056 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontTimes1b_0057 } /* code 0057 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_0058 } /* code 0058 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_0059 } /* code 0059 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_005A } /* code 005A */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_005B } /* code 005B */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_005C } /* code 005C */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_005D } /* code 005D */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_005E } /* code 005E */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_005F } /* code 005F */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_0060 } /* code 0060 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0061 } /* code 0061 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0062 } /* code 0062 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0063 } /* code 0063 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0064 } /* code 0064 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0065 } /* code 0065 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_0066 } /* code 0066 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0067 } /* code 0067 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0068 } /* code 0068 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_0069 } /* code 0069 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_006A } /* code 006A */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_006B } /* code 006B */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_006C } /* code 006C */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_006D } /* code 006D */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_006E } /* code 006E */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_006F } /* code 006F */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0070 } /* code 0070 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0071 } /* code 0071 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0072 } /* code 0072 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_0073 } /* code 0073 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_0074 } /* code 0074 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0075 } /* code 0075 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0076 } /* code 0076 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_0077 } /* code 0077 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0078 } /* code 0078 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_0079 } /* code 0079 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_007A } /* code 007A */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_007B } /* code 007B */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_007C } /* code 007C */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_007D } /* code 007D */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_007E } /* code 007E */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_007F } /* code 007F */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_00A0 } /* code 00A0 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_00A1 } /* code 00A1 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00A2 } /* code 00A2 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00A3 } /* code 00A3 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00A4 } /* code 00A4 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00A5 } /* code 00A5 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_00A6 } /* code 00A6 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00A7 } /* code 00A7 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_00A8 } /* code 00A8 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00A9 } /* code 00A9 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_00AA } /* code 00AA */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00AB } /* code 00AB */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_00AC } /* code 00AC */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_00AD } /* code 00AD */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00AE } /* code 00AE */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00AF } /* code 00AF */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_00B0 } /* code 00B0 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00B1 } /* code 00B1 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_00B2 } /* code 00B2 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_00B3 } /* code 00B3 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_00B4 } /* code 00B4 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_00B5 } /* code 00B5 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00B6 } /* code 00B6 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_00B7 } /* code 00B7 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_00B8 } /* code 00B8 */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_00B9 } /* code 00B9 */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_00BA } /* code 00BA */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00BB } /* code 00BB */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00BC } /* code 00BC */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00BD } /* code 00BD */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00BE } /* code 00BE */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00BF } /* code 00BF */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00C0 } /* code 00C0 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00C1 } /* code 00C1 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00C2 } /* code 00C2 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00C3 } /* code 00C3 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00C4 } /* code 00C4 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00C5 } /* code 00C5 */
  ,{   8,   8,  1, (void GUI_FLASH *)&acFontTimes1b_00C6 } /* code 00C6 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00C7 } /* code 00C7 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_00C8 } /* code 00C8 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_00C9 } /* code 00C9 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_00CA } /* code 00CA */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_00CB } /* code 00CB */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_00CC } /* code 00CC */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_00CD } /* code 00CD */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_00CE } /* code 00CE */
  ,{   3,   3,  1, (void GUI_FLASH *)&acFontTimes1b_00CF } /* code 00CF */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00D0 } /* code 00D0 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00D1 } /* code 00D1 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00D2 } /* code 00D2 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00D3 } /* code 00D3 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00D4 } /* code 00D4 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00D5 } /* code 00D5 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00D6 } /* code 00D6 */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_00D7 } /* code 00D7 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00D8 } /* code 00D8 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00D9 } /* code 00D9 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00DA } /* code 00DA */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00DB } /* code 00DB */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00DC } /* code 00DC */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00DD } /* code 00DD */
  ,{   5,   5,  1, (void GUI_FLASH *)&acFontTimes1b_00DE } /* code 00DE */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00DF } /* code 00DF */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00E0 } /* code 00E0 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00E1 } /* code 00E1 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00E2 } /* code 00E2 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00E3 } /* code 00E3 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00E4 } /* code 00E4 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00E5 } /* code 00E5 */
  ,{   6,   6,  1, (void GUI_FLASH *)&acFontTimes1b_00E6 } /* code 00E6 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00E7 } /* code 00E7 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00E8 } /* code 00E8 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00E9 } /* code 00E9 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00EA } /* code 00EA */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00EB } /* code 00EB */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_00EC } /* code 00EC */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_00ED } /* code 00ED */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_00EE } /* code 00EE */
  ,{   2,   2,  1, (void GUI_FLASH *)&acFontTimes1b_00EF } /* code 00EF */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00F0 } /* code 00F0 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00F1 } /* code 00F1 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00F2 } /* code 00F2 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00F3 } /* code 00F3 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00F4 } /* code 00F4 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00F5 } /* code 00F5 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00F6 } /* code 00F6 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00F7 } /* code 00F7 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00F8 } /* code 00F8 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00F9 } /* code 00F9 */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00FA } /* code 00FA */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00FB } /* code 00FB */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00FC } /* code 00FC */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00FD } /* code 00FD */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00FE } /* code 00FE */
  ,{   4,   4,  1, (void GUI_FLASH *)&acFontTimes1b_00FF } /* code 00FF */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontTimes1b_Prop2 = {
   0x00A0 /* first character */
  ,0x00FF /* last character  */
  ,&GUI_FontTimes1b_CharInfo[ 96] /* address of first character */
  ,(void*)0 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontTimes1b_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_FontTimes1b_CharInfo[  0] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontTimes1b_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT GUI_FontTimes1b = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,11 /* height of font  */
  ,11 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,(void GUI_FLASH *)&GUI_FontTimes1b_Prop1
};

