#ifndef __LISTENER_HPP__
#define __LISTENER_HPP__

#include "webctypes.h"

class Notifier
{
	int i;
};

enum NotifierType
{
	NOTIFIER_TYPE_NONE,
	NOTIFIER_TYPE_HTML_ELEMENT,
	NOTIFIER_TYPE_DISPLAY_ELEMENT,
	NOTIFIER_TYPE_IMAGE,
	NOTIFIER_TYPE_BUTTON,
	NOTIFIER_TYPE_SELECT,
	NOTIFIER_TYPE_EDIT,
	NOTIFIER_TYPE_SLIDER,
	NOTIFIER_TYPE_TEXT_UNIT,
	NOTIFIER_TYPE_RADIO_BUTTON,
	NOTIFIER_TYPE_LIST_BOX,
	NOTIFIER_TYPE_DISPLAY_MANAGER,
	NOTIFIER_TYPE_NODISPLAY_HTML_CHILD,
	NOTIFIER_TYPE_CHILD_TABLE_ROW
};

enum NotifyEventType
{
	NOTIFY_UNKNOWN_EVENT = -1,
	NOTIFY_BITMAP_CHANGE = 0,
	NOTIFY_BUTTON_DOWN,
	NOTIFY_BUTTON_PRESS,
	NOTIFY_BUTTON_UP,
	NOTIFY_CONTENT_ADDED,
	NOTIFY_CONTENT_REMOVED,
	NOTIFY_DISPLAY_STYLE_CHANGE, // does not affect formatting
	NOTIFY_DONE,
	NOTIFY_FLOW_CHILD_STYLE_CHANGE,
	NOTIFY_FOCUS_LOST,
	NOTIFY_FORMAT_STYLE_CHANGE,
	NOTIFY_MAX_WIDTH_CHANGE,
	NOTIFY_MIN_WIDTH_CHANGE,
	NOTIFY_PARENT_DISPLAY_STYLE_CHANGE,
	NOTIFY_PARENT_STYLE_CHANGE,
	NOTIFY_POSITIONED_CHILD_STYLE_CHANGE,
	NOTIFY_SELECT_CHANGE,
	NOTIFY_SIZE_CHANGE,
	NOTIFY_SLIDER_MOVE,
	NOTIFY_STYLE_CHANGE,
	NOTIFY_TEXT_EDIT,
	NOTIFY_WEB_GRAPHICS_CHANGE,
	NOTIFY_ZINDEX_CHANGE,
	NOTIFY_RENDER_FIRST_STATE,
	NOTIFY_RENDER_DRAW_START,
	NOTIFY_RENDER_DRAW_DONE,
	NOTIFY_RENDER_LAST_STATE,
	NUM_NOTIFIY_EVENTS
};

class WebcImage;

struct NotifyEvent
{
	NotifyEvent (NotifierType t, NotifyEventType e)
	{
		type = t;
		event = e;
	}

	NotifierType    type;
	NotifyEventType event;

	union
	{
		WebcImage *image;
		WEBC_UINT8 pad;

		struct
		{
			WEBC_UINT16 display;
			WEBC_UINT16 position;
		} oldStyle;
	} data;
};

class Listener
{
public:
    virtual void Notify (Notifier *who, NotifyEvent *what) = 0;

};


#endif // __LISTENER_HPP__
